//! The `rails/1` orphan report, v1 — a TRIAGE QUEUE, never a verdict.
//!
//! Six lanes, each of which names the witness that produced it and the
//! reason it might be wrong. Every input is a `rails-lens/1` convention
//! edge capped at `likely`/`candidate`, so the whole report inherits that
//! cap: "no render edge targets this template" is a statement about the
//! lens's coverage, not about the application. The report says so in
//! [`CAPTION`], in every lane's own `why`, and — where the lens has a
//! measurable blind spot in THIS repo (a template language it does not
//! read, a dynamic render it refuses to guess) — in the lane's `notes`.
//!
//! Nothing here is stored, ranked or scored. A row is an address plus its
//! evidence; the ordering is the noun's own alphabetical order, so two runs
//! over one tree produce the same report.

use super::{Honesty, RailsIndex, RailsRow, Witness, SCHEMA};
use crate::frameworks::{EdgeKind, Trust};
use serde::Serialize;
use std::collections::HashSet;

/// Rows kept per lane. A lane over its cap reports the TRUE total beside
/// the page and sets `truncated`.
pub const MAX_LANE_ROWS: usize = 200;

pub const CAPTION: &str = "Every lane below is derived from rails-lens/1 convention edges, which \
are capped at likely/candidate by construction — this is a triage queue to \
read, never a verdict to act on unread. A row can be wrong because the lens \
does not read a template language this app uses, because a render or an \
enqueue is dynamic and the lens refuses to guess it, or because a constant \
is reached by plain Ruby the lens does not model.";

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct OrphanRow {
    pub name: String,
    pub path: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub line: Option<u32>,
    pub trust: Trust,
    pub witnesses: Vec<Witness>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct OrphanLane {
    pub id: &'static str,
    pub title: &'static str,
    /// The witness, stated: what produced this lane and why it may be wrong.
    pub why: &'static str,
    pub rows: Vec<OrphanRow>,
    pub total: usize,
    pub returned: usize,
    pub truncated: bool,
    pub state: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize)]
pub struct OrphansOut {
    pub schema: &'static str,
    pub repo: String,
    pub caption: &'static str,
    pub lanes: Vec<OrphanLane>,
    pub honesty: Honesty,
    pub notes: Vec<String>,
}

fn lane(
    id: &'static str,
    title: &'static str,
    why: &'static str,
    mut rows: Vec<OrphanRow>,
    unavailable: Option<String>,
) -> OrphanLane {
    rows.sort_by(|a, b| a.name.cmp(&b.name).then_with(|| a.path.cmp(&b.path)));
    let total = rows.len();
    let truncated = total > MAX_LANE_ROWS;
    rows.truncate(MAX_LANE_ROWS);
    let returned = rows.len();
    let (state, reason) = match (&unavailable, total) {
        (Some(r), _) => ("unavailable", Some(r.clone())),
        (None, 0) => (
            "empty",
            Some("no rows — this lane found nothing, which is not the same as a clean bill of health (see the report caption)".to_string()),
        ),
        _ => ("ok", None),
    };
    OrphanLane {
        id,
        title,
        why,
        rows,
        total,
        returned,
        truncated,
        state,
        reason,
    }
}

fn row_of(r: &RailsRow) -> OrphanRow {
    OrphanRow {
        name: r.name.clone(),
        path: r.path.clone(),
        line: r.line,
        trust: r.trust,
        witnesses: r.witnesses.clone(),
    }
}

/// Build the whole report from an already-joined index. Pure apart from the
/// locale-key lane, which reads the lens's own fingerprint-cached locale
/// index — the caller runs this on the blocking pool for that one reason.
pub fn build_report(repo: &str, idx: &RailsIndex, repo_root: &std::path::Path) -> OrphansOut {
    let mut lanes = Vec::new();

    // 1. routes whose target action was not found.
    lanes.push(lane(
        "route_without_action",
        "Routes with no reachable action",
        "the routes DSL names controller#action; no public method of that name was found in the \
         controller the naming convention points at. Wrong when the action is inherited from a \
         superclass or generated by a gem — neither is indexed.",
        idx.rows("route")
            .iter()
            .filter(|r| {
                r.flags.contains(&"action-missing") || r.flags.contains(&"controller-missing")
            })
            .map(row_of)
            .collect(),
        None,
    ));

    // 2. public controller actions no route reaches.
    let visibility_unknown = idx
        .rows("action")
        .iter()
        .any(|r| r.flags.contains(&"visibility-unknown"));
    lanes.push(lane(
        "action_without_route",
        "Public controller actions with no route",
        "a method in a controller class that no route_action edge targets. Method VISIBILITY is \
         not indexed — it is read with a line scan for a bare `private`/`protected`, which misses \
         the `private def foo` and `private :foo` forms, so a private helper can appear here.",
        idx.rows("action")
            .iter()
            .filter(|r| r.counts.get("routes").copied().unwrap_or(0) == 0)
            .map(row_of)
            .collect(),
        None,
    ));
    if visibility_unknown {
        if let Some(l) = lanes.last_mut() {
            l.reason = Some(
                "some controllers were past this request's visibility read budget; their methods \
                 are listed with visibility \"unknown\""
                    .to_string(),
            );
        }
    }

    // 3. templates no render edge reaches.
    lanes.push(lane(
        "view_never_rendered",
        "Views never rendered by any render edge",
        "no render_view/render_partial/view_component_render edge targets this template. Render \
         edges are convention-derived and the lens refuses a dynamic `render(some_variable)` \
         rather than guessing it, so a reachable template can appear here.",
        idx.rows("view")
            .iter()
            .filter(|r| r.counts.get("rendered_by").copied().unwrap_or(0) == 0)
            .map(row_of)
            .collect(),
        None,
    ));

    // 4. models with no inbound edge from any other file.
    let inbound_from_elsewhere: HashSet<&str> = idx
        .edges
        .iter()
        .filter_map(|e| {
            let dst = e.dst_path.as_deref()?;
            (dst != e.src_path).then_some(dst)
        })
        .collect();
    lanes.push(lane(
        "model_referenced_only_from_its_own_file",
        "Models referenced only from their own file",
        "no rails-lens edge from any OTHER file points at this model file. Plain Ruby references \
         (a constant used in a service object, a bare `Order.find`) are not modelled by this lens \
         at all, so this lane is a starting point for a usages check, not evidence of dead code.",
        idx.rows("model")
            .iter()
            .filter(|r| !inbound_from_elsewhere.contains(r.path.as_str()))
            .map(row_of)
            .collect(),
        None,
    ));

    // 5. jobs never enqueued.
    lanes.push(lane(
        "job_never_enqueued",
        "Jobs never enqueued",
        "no job_enqueue edge targets this job class. The lens reads `.perform_later`/\
         `.perform_now` call sites in the file trees it dispatches; a job enqueued from an \
         undispatched tree, from a cron schedule file, or through a class-name STRING is invisible \
         to it.",
        idx.rows("job")
            .iter()
            .filter(|r| r.counts.get("enqueue_sites").copied().unwrap_or(0) == 0)
            .map(row_of)
            .collect(),
        None,
    ));

    // 6. locale keys nothing references.
    lanes.push(locale_lane(idx, repo_root));

    let notes = vec![
        "counts are TRUE totals over the whole index; a lane past its cap reports the total \
         beside the page and sets truncated"
            .to_string(),
        "the report is recomputed per request and stored nowhere".to_string(),
    ];
    let any_rows = lanes.iter().any(|l| l.total > 0);
    let honesty = if !idx.detected {
        Honesty::empty(
            idx.detect_reason
                .clone()
                .unwrap_or_else(|| "not a Rails application".to_string()),
        )
    } else if !idx.budgets.is_empty() {
        Honesty::partial(idx.budgets.join("; "))
    } else if !any_rows {
        Honesty::empty("every lane is empty — see each lane's own reason".to_string())
    } else {
        Honesty::ok()
    };

    OrphansOut {
        schema: SCHEMA,
        repo: repo.to_string(),
        caption: CAPTION,
        lanes,
        honesty,
        notes,
    }
}

/// Locale keys the lens never saw referenced. Cheap because the locale
/// index is the lens's OWN fingerprint-cached one (invariant 12(b)) — this
/// route pays a `stat` per locale file on a warm cache, not a re-parse.
/// The locale keys nothing references, from a `(file, key)` index and the
/// set of keys `rails-lens/1` saw referenced.
///
/// Two rules, both of which the naive "key not in the referenced set" form
/// gets wrong on a real locale tree, because `crate::yaml::outline` emits
/// EVERY node of the key path, not only the leaves:
///
/// * a CONTAINER is not a translation key — `orders.index` exists only
///   because `orders.index.title` does, and listing it as unused is noise;
/// * referencing a key USES its ancestors — `t("orders.index.title")`
///   means `orders` and `orders.index` are reached, not orphaned.
///
/// Both are decided without an O(n²) scan: ancestors are expanded from the
/// (small) referenced set once, and containment is a single sorted-neighbour
/// check. Duplicate keys across locale files are reported once, under the
/// first file that defines them, in the index's own order.
pub(crate) fn unused_locale_keys<'a>(
    index: &'a [(String, String)],
    referenced: &HashSet<&str>,
) -> Vec<(&'a String, &'a String)> {
    // Every referenced key AND every ancestor of one counts as reached.
    let mut used: HashSet<String> = HashSet::new();
    for r in referenced {
        let mut acc = String::new();
        for seg in r.split('.') {
            if !acc.is_empty() {
                acc.push('.');
            }
            acc.push_str(seg);
            used.insert(acc.clone());
        }
    }
    let mut sorted: Vec<&str> = index.iter().map(|(_, k)| k.as_str()).collect();
    sorted.sort_unstable();
    sorted.dedup();
    let is_container = |k: &str| match sorted.binary_search(&k) {
        Ok(i) => sorted.get(i + 1).is_some_and(|next| {
            next.len() > k.len() && next.starts_with(k) && next.as_bytes()[k.len()] == b'.'
        }),
        Err(_) => false,
    };

    let mut seen: HashSet<&str> = HashSet::new();
    let mut out = Vec::new();
    for (file, key) in index {
        if used.contains(key.as_str()) || is_container(key.as_str()) {
            continue;
        }
        if seen.insert(key.as_str()) {
            out.push((file, key));
        }
    }
    out
}

fn locale_lane(idx: &RailsIndex, repo_root: &std::path::Path) -> OrphanLane {
    const WHY: &str = "the key appears in a config/locales YAML file and no i18n_key edge names \
it. The lens resolves `t(\"literal\")` only: an interpolated key, a lazy `t(\".relative\")` and \
every call site in a template language the lens does not read are all invisible to it, and a \
key referenced only from one of those looks unused here.";

    let referenced: HashSet<&str> = idx
        .edges
        .iter()
        .filter(|e| e.kind == EdgeKind::I18nKey)
        .filter_map(|e| e.dst_symbol.as_deref())
        .collect();
    let index = crate::frameworks::rails::i18n::locale_index_for(repo_root);
    if index.is_empty() {
        return lane(
            "locale_key_never_referenced",
            "Locale keys never referenced",
            WHY,
            Vec::new(),
            Some("no locale keys were found under config/locales".to_string()),
        );
    }
    let unused = unused_locale_keys(&index, &referenced);
    let mut rows = Vec::new();
    for (file, key) in unused {
        rows.push(OrphanRow {
            name: key.clone(),
            path: file.clone(),
            line: None,
            // A key's absence from the edge set is the weakest evidence in
            // this report: it is bounded by the lens's template coverage.
            trust: Trust::Candidate,
            witnesses: vec![Witness {
                kind: "convention",
                detail: format!("defined in {file}; no rails-lens/1 i18n_key edge names it"),
                path: Some(file.clone()),
                line: None,
                trust: None,
            }],
        });
    }
    lane(
        "locale_key_never_referenced",
        "Locale keys never referenced",
        WHY,
        rows,
        None,
    )
}
