//! `comments/1` — the kind taxonomy (D8).
//!
//! Eight kinds, classified in a FIXED precedence so the answer never
//! depends on evaluation order: `generated` and `licence` are decided for
//! a whole RUN of adjacent comment lines, then `commented_code` for a run
//! nothing else claimed, then `directive`/`annotation`/`section` per LINE,
//! then `doc` (a run that sits immediately above a definition) and finally
//! `prose`.
//!
//! ## Why `generated` outranks `doc`
//!
//! A schema-dump banner (`# == Schema Information`, written by a
//! generator and refreshed on migrate) sits immediately above a class
//! with no blank line between them. The pre-`comments/1` doc capture
//! (`extract::capture_doc`, which accepts ANY Ruby comment as doc)
//! therefore reported a column dump as the class's documentation. That is
//! not a tuning problem, it is an ordering one: a block that announces
//! itself as machine-written is never documentation, whatever it is
//! adjacent to.
//!
//! ## Why `commented_code` is a parse, not a regex
//!
//! "Does this text parse as code" has an exact answer for any language
//! with a grammar, and this crate already links eleven. The run's text is
//! re-parsed with the FILE's own grammar and accepted only with zero
//! ERROR/MISSING nodes, behind a cheap punctuation pre-gate (so ordinary
//! prose never pays for a parse) and a shape guard (two lines, or a
//! statement-shaped top-level node) so a single bare word cannot qualify.
//! `bash` is deliberately EXCLUDED: its grammar accepts an arbitrary
//! sequence of words as a command, so the parse carries no signal there
//! and an English sentence would classify as code.

use crate::comments::keywords::KeywordSet;
use serde::{Deserialize, Serialize};

/// The kind vocabulary. Closed — a value outside it is unrepresentable
/// rather than a string a route could invent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CommentKind {
    Doc,
    Annotation,
    Directive,
    Section,
    Licence,
    Generated,
    CommentedCode,
    Prose,
}

impl CommentKind {
    pub const ALL: &'static [CommentKind] = &[
        CommentKind::Doc,
        CommentKind::Annotation,
        CommentKind::Directive,
        CommentKind::Section,
        CommentKind::Licence,
        CommentKind::Generated,
        CommentKind::CommentedCode,
        CommentKind::Prose,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            CommentKind::Doc => "doc",
            CommentKind::Annotation => "annotation",
            CommentKind::Directive => "directive",
            CommentKind::Section => "section",
            CommentKind::Licence => "licence",
            CommentKind::Generated => "generated",
            CommentKind::CommentedCode => "commented_code",
            CommentKind::Prose => "prose",
        }
    }

    pub fn parse(s: &str) -> Option<CommentKind> {
        CommentKind::ALL.iter().copied().find(|k| k.as_str() == s)
    }
}

/// How many lines from the top of a file a run may start and still be
/// eligible for `licence` (a copyright notice in the middle of a file is
/// prose about licensing, not the file's header).
pub const LICENCE_HEAD_LINES: u32 = 12;

/// Case-insensitive needles that make a run `generated`. `== Schema
/// Information` is the annotate-gem banner named in D8.
const GENERATED_NEEDLES: &[&str] = &[
    "== schema information",
    "do not edit",
    "don't edit",
    "code generated by",
    "@generated",
    "autogenerated",
    "auto-generated",
    "automatically generated",
    "this file is generated",
    "generated file",
];

/// Case-insensitive needles that make a head-of-file run `licence`.
const LICENCE_NEEDLES: &[&str] = &[
    "spdx-license-identifier",
    "copyright (c)",
    "copyright ©",
    "copyright 19",
    "copyright 20",
    "all rights reserved",
    "licensed under",
    "this program is free software",
    "permission is hereby granted",
    "gnu general public license",
];

/// Section-banner lead-ins (matched at the start of the stripped text,
/// case-sensitively for the shouty ones).
const SECTION_LEAD_INS: &[&str] = &[
    "region ",
    "endregion",
    "#region",
    "#endregion",
    "SECTION",
    "!SECTION",
    "MARK:",
    "MARK -",
    "pragma mark",
];

/// Characters a rule/banner is drawn from.
const RULE_CHARS: &[char] = &['-', '=', '*', '~', '_', '+', '#', '/'];

/// One recognised directive family.
#[derive(Debug, Clone, Copy)]
pub struct DirectiveSpec {
    /// Lowercased prefix matched at the START of the stripped comment
    /// text (the shape every one of these actually takes in the wild).
    pub prefix: &'static str,
    /// The `directive_tool` recorded on the row.
    pub tool: &'static str,
    /// A SUPPRESSION directive silences a checker; only these can be
    /// `unreasoned`. A magic comment / build tag carries a VALUE, not a
    /// justification, and never gets a state.
    pub suppression: bool,
    /// Whether the directive is followed by its own argument list (cop
    /// names, rule ids, error codes). See [`has_reason`].
    pub takes_args: bool,
}

/// The closed directive vocabulary. Additive by construction: one row
/// here is the whole change.
pub const DIRECTIVES: &[DirectiveSpec] = &[
    // Ruby / RuboCop
    DirectiveSpec {
        prefix: "rubocop:disable",
        tool: "rubocop",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "rubocop:todo",
        tool: "rubocop",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "rubocop:enable",
        tool: "rubocop",
        suppression: false,
        takes_args: true,
    },
    // Ruby magic comments (a VALUE, never a justification)
    DirectiveSpec {
        prefix: "frozen_string_literal:",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "encoding:",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "coding:",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "warn_indent:",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "shareable_constant_value:",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "-*-",
        tool: "ruby-magic",
        suppression: false,
        takes_args: true,
    },
    // Sorbet / RBS
    DirectiveSpec {
        prefix: "typed:",
        tool: "sorbet",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "@rbs",
        tool: "rbs",
        suppression: false,
        takes_args: true,
    },
    // JS / TS
    DirectiveSpec {
        prefix: "eslint-disable-next-line",
        tool: "eslint",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "eslint-disable-line",
        tool: "eslint",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "eslint-disable",
        tool: "eslint",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "eslint-enable",
        tool: "eslint",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "eslint-env",
        tool: "eslint",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "@ts-expect-error",
        tool: "ts",
        suppression: true,
        takes_args: false,
    },
    DirectiveSpec {
        prefix: "@ts-ignore",
        tool: "ts",
        suppression: true,
        takes_args: false,
    },
    DirectiveSpec {
        prefix: "@ts-nocheck",
        tool: "ts",
        suppression: true,
        takes_args: false,
    },
    DirectiveSpec {
        prefix: "prettier-ignore",
        tool: "prettier",
        suppression: true,
        takes_args: false,
    },
    DirectiveSpec {
        prefix: "biome-ignore",
        tool: "biome",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "istanbul ignore",
        tool: "istanbul",
        suppression: true,
        takes_args: true,
    },
    // Python
    DirectiveSpec {
        prefix: "noqa",
        tool: "flake8",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "type: ignore",
        tool: "mypy",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "pylint:",
        tool: "pylint",
        suppression: true,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "pragma: no cover",
        tool: "coverage",
        suppression: true,
        takes_args: false,
    },
    // Rust — `#[allow(...)]` is an ATTRIBUTE, not a comment, and is
    // deliberately out of scope; these are the comment-shaped ones.
    DirectiveSpec {
        prefix: "rustfmt::skip",
        tool: "rustfmt",
        suppression: true,
        takes_args: false,
    },
    DirectiveSpec {
        prefix: "clippy::",
        tool: "clippy",
        suppression: true,
        takes_args: true,
    },
    // Go
    DirectiveSpec {
        prefix: "go:build",
        tool: "go",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "+build",
        tool: "go",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "go:generate",
        tool: "go",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "nolint",
        tool: "golangci-lint",
        suppression: true,
        takes_args: true,
    },
    // Shell
    DirectiveSpec {
        prefix: "shellcheck",
        tool: "shellcheck",
        suppression: true,
        takes_args: true,
    },
    // YAML / editors
    DirectiveSpec {
        prefix: "yaml-language-server:",
        tool: "yaml-language-server",
        suppression: false,
        takes_args: true,
    },
    DirectiveSpec {
        prefix: "yamllint",
        tool: "yamllint",
        suppression: true,
        takes_args: true,
    },
];

/// The recognised directive on one stripped comment line, if any.
///
/// `rbs_inline` handles `#: () -> String`, whose marker is the colon
/// glued to the comment sigil rather than a word.
pub fn directive_of(
    stripped: &str,
    sigil_had_colon: bool,
) -> Option<(&'static DirectiveSpec, bool)> {
    if sigil_had_colon {
        static RBS_INLINE: DirectiveSpec = DirectiveSpec {
            prefix: "#:",
            tool: "rbs",
            suppression: false,
            takes_args: true,
        };
        return Some((&RBS_INLINE, true));
    }
    let lower = stripped.to_ascii_lowercase();
    let spec = DIRECTIVES.iter().find(|d| lower.starts_with(d.prefix))?;
    let rest = &stripped[spec.prefix.len()..];
    Some((spec, has_reason(spec, rest)))
}

/// Whether a directive carries a human justification.
///
/// For a directive with NO argument list (`@ts-expect-error`,
/// `prettier-ignore`), any trailing text is the reason. For one that DOES
/// take arguments (cop names, rule ids, error codes), a reason must be
/// SEPARATED (`--`, an en/em dash, or a nested `#`) — free text after a
/// cop list is indistinguishable from another cop name, and `--` is the
/// separator RuboCop itself documents for exactly this. A rule that
/// guessed instead would report "unreasoned" as a verdict, which is the
/// one thing this lane must never do.
pub fn has_reason(spec: &DirectiveSpec, rest: &str) -> bool {
    let rest = rest.trim_start_matches([':', '=', ' ', '\t']).trim();
    if !spec.takes_args {
        return !rest.is_empty();
    }
    for sep in [" -- ", " – ", " — ", " # "] {
        if let Some((_, reason)) = rest.split_once(sep) {
            if !reason.trim().is_empty() {
                return true;
            }
        }
    }
    // A trailing separator with nothing after it is not a reason.
    false
}

/// Does this run announce itself as machine-written?
pub fn is_generated(lines: &[String]) -> bool {
    lines.iter().any(|l| {
        let lower = l.to_ascii_lowercase();
        GENERATED_NEEDLES.iter().any(|n| lower.contains(n))
    })
}

/// Is this a file-header licence block?
pub fn is_licence(first_line_no: u32, lines: &[String]) -> bool {
    if first_line_no > LICENCE_HEAD_LINES {
        return false;
    }
    lines.iter().any(|l| {
        let lower = l.to_ascii_lowercase();
        LICENCE_NEEDLES.iter().any(|n| lower.contains(n))
    })
}

/// Is this line a section banner / fold marker?
pub fn is_section(stripped: &str) -> bool {
    let t = stripped.trim();
    if t.len() >= 3 && t.chars().all(|c| RULE_CHARS.contains(&c)) {
        return true;
    }
    if SECTION_LEAD_INS.iter().any(|p| t.starts_with(p)) {
        return true;
    }
    // `==== Name ====` / `--- x ---`: at least two rule chars on BOTH
    // ends with something between them.
    let lead = t.chars().take_while(|c| RULE_CHARS.contains(c)).count();
    let trail = t
        .chars()
        .rev()
        .take_while(|c| RULE_CHARS.contains(c))
        .count();
    lead >= 2 && trail >= 2 && t.chars().count() > lead + trail
}

/// Does this line carry an annotation keyword?
pub fn annotation_of(
    set: &KeywordSet,
    stripped: &str,
) -> Option<crate::comments::keywords::KeywordHit> {
    set.find(stripped)
}

/// Languages whose grammar makes the `commented_code` parse probe
/// meaningful. `bash` is excluded on purpose (see the module doc); the
/// three outline-tier languages (yaml/toml/json) and `erb` have no
/// statement grammar to probe with.
pub const CODE_PROBE_LANG_IDS: &[&str] = &[
    "rust",
    "python",
    "ruby",
    "typescript",
    "tsx",
    "javascript",
    "go",
];

/// The cheap pre-gate: a run without one of these never pays for a parse.
///
/// This list is DELIBERATELY strict, and the strictness is the fix for a
/// real false positive. Ruby (like bash) accepts a bare sequence of words
/// as a command call, so `Returns the total (in cents)` parses with ZERO
/// error nodes and its top-level node is a `call` — every downstream guard
/// passes, and an English sentence classifies as commented-out code. What
/// separates the two is not the parse: it is that real code carries an
/// OPERATOR or an adjacent-paren call (`compute(1)`), while prose puts a
/// space before its parenthetical. Under-detecting a commented-out `# puts
/// x` is the acceptable side of that trade; calling a doc comment "code"
/// is not.
const CODE_SIGNALS: &[&str] = &[
    "=", ";", "{", "}", "[", "]", "::", "->", "=>", "&&", "||", "<<",
];

/// Does this text carry a code signal — one of [`CODE_SIGNALS`], or a call
/// whose `(` touches its callee?
fn has_code_signal(text: &str) -> bool {
    if CODE_SIGNALS.iter().any(|p| text.contains(p)) {
        return true;
    }
    text.as_bytes()
        .windows(2)
        .any(|w| (w[0].is_ascii_alphanumeric() || w[0] == b'_') && w[1] == b'(')
}

/// Top-level node kinds that count as "a statement, not a bare word" —
/// the shape guard that stops a single identifier from qualifying.
fn is_statement_kind(kind: &str) -> bool {
    kind.contains("statement")
        || kind.contains("declaration")
        || kind.contains("definition")
        || kind.contains("assignment")
        || kind.contains("call")
        || kind.contains("_item")
        || matches!(
            kind,
            "method" | "class" | "module" | "if" | "unless" | "while" | "for"
        )
}

/// Does this run's text parse as code in its own file's language?
pub fn looks_like_code(lang_id: &str, lines: &[String]) -> bool {
    if !CODE_PROBE_LANG_IDS.contains(&lang_id) {
        return false;
    }
    let text = lines.join("\n");
    let trimmed = text.trim();
    if trimmed.is_empty() || !has_code_signal(trimmed) {
        return false;
    }
    let Ok((tree, _)) = crate::lang::parse(lang_id, text.as_bytes()) else {
        return false;
    };
    let root = tree.root_node();
    if root.has_error() {
        return false;
    }
    if root.named_child_count() == 0 {
        return false;
    }
    if lines.len() >= 2 {
        return true;
    }
    root.named_child(0)
        .map(|n| is_statement_kind(n.kind()))
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &[&str]) -> Vec<String> {
        v.iter().map(|x| (*x).to_string()).collect()
    }

    #[test]
    fn kind_names_round_trip() {
        for k in CommentKind::ALL {
            assert_eq!(CommentKind::parse(k.as_str()), Some(*k));
        }
        assert!(CommentKind::parse("nope").is_none());
    }

    #[test]
    fn the_schema_banner_is_generated_never_doc() {
        assert!(is_generated(&s(&[
            "== Schema Information",
            "Table name: orders",
            "  id  :bigint  not null, primary key",
        ])));
    }

    #[test]
    fn generated_markers_are_case_insensitive() {
        for l in [
            "Code generated by protoc. DO NOT EDIT.",
            "@generated",
            "This file is generated; do not edit",
        ] {
            assert!(is_generated(&s(&[l])), "{l}");
        }
        assert!(!is_generated(&s(&["ordinary prose about editing"])));
    }

    #[test]
    fn licence_needs_the_head_of_the_file() {
        let lines = s(&["SPDX-License-Identifier: MIT"]);
        assert!(is_licence(1, &lines));
        assert!(!is_licence(LICENCE_HEAD_LINES + 1, &lines));
    }

    #[test]
    fn section_banners_of_several_shapes() {
        for l in [
            "====================",
            "==== Callbacks ====",
            "--- private helpers ---",
            "region Validations",
            "SECTION Ordering",
            "MARK: setup",
        ] {
            assert!(is_section(l), "{l}");
        }
        for l in ["Returns the total", "a - b", "TODO: not a banner"] {
            assert!(!is_section(l), "{l}");
        }
    }

    #[test]
    fn directives_are_recognised_with_their_tool() {
        let cases = [
            ("rubocop:disable Metrics/AbcSize", "rubocop", false),
            (
                "rubocop:disable Metrics/AbcSize -- legacy import path",
                "rubocop",
                true,
            ),
            ("rubocop:enable Metrics/AbcSize", "rubocop", false),
            ("frozen_string_literal: true", "ruby-magic", false),
            ("typed: strict", "sorbet", false),
            ("eslint-disable-next-line no-console", "eslint", false),
            (
                "eslint-disable-next-line no-console -- vendor script",
                "eslint",
                true,
            ),
            ("@ts-expect-error the upstream type is wrong", "ts", true),
            ("@ts-expect-error", "ts", false),
            ("noqa: E501", "flake8", false),
            ("type: ignore[attr-defined]", "mypy", false),
            ("go:build linux", "go", false),
            ("shellcheck disable=SC2086", "shellcheck", false),
        ];
        for (line, tool, reason) in cases {
            let (spec, has) = directive_of(line, false)
                .unwrap_or_else(|| panic!("{line:?} should be a directive"));
            assert_eq!(spec.tool, tool, "{line}");
            assert_eq!(has, reason, "{line}: has_reason");
        }
        assert!(directive_of("Returns the total", false).is_none());
        // A keyword line is never a directive — the keyword is not at the
        // start in a directive shape.
        assert!(directive_of("TODO: rubocop:disable something", false).is_none());
    }

    #[test]
    fn rbs_inline_rides_the_sigil_not_a_word() {
        let (spec, _) = directive_of("() -> String", true).unwrap();
        assert_eq!(spec.tool, "rbs");
    }

    #[test]
    fn only_suppression_directives_can_be_unreasoned() {
        let magic = DIRECTIVES
            .iter()
            .find(|d| d.prefix == "frozen_string_literal:")
            .unwrap();
        assert!(!magic.suppression);
        let disable = DIRECTIVES
            .iter()
            .find(|d| d.prefix == "rubocop:disable")
            .unwrap();
        assert!(disable.suppression);
    }

    #[test]
    fn commented_out_code_parses_prose_does_not() {
        assert!(looks_like_code(
            "ruby",
            &s(&["order.total = 0", "order.save!"])
        ));
        assert!(looks_like_code("rust", &s(&["let x = compute(1);"])));
        assert!(looks_like_code(
            "python",
            &s(&["def old(a):", "    return a + 1"])
        ));
        for prose in [
            // The regression that made `CODE_SIGNALS` strict: Ruby parses
            // this as a command call with zero errors, so only the SPACE
            // before its parenthetical tells it from `compute(1)`.
            s(&["Returns the total (in cents)"]),
            s(&[
                "Returns the order total in cents.",
                "Falls back to the id when the name is blank.",
            ]),
            s(&["See the README for details"]),
            s(&["This is why we do it this way"]),
        ] {
            assert!(!looks_like_code("ruby", &prose), "{prose:?}");
        }
    }

    #[test]
    fn bash_is_excluded_from_the_code_probe() {
        // The bash grammar accepts any word sequence as a command, so the
        // parse carries no signal — an English sentence would qualify.
        assert!(!looks_like_code("bash", &s(&["Set FOO=bar to enable"])));
        assert!(!looks_like_code(
            "bash",
            &s(&["rm -rf \"$dir\"; echo done"])
        ));
    }

    #[test]
    fn outline_tier_languages_never_probe_for_code() {
        for id in ["yaml", "toml", "json", "erb"] {
            assert!(!looks_like_code(id, &s(&["a = (1)"])), "{id}");
        }
    }

    #[test]
    fn the_code_signal_gate_separates_an_operator_from_a_parenthetical() {
        assert!(has_code_signal("order.total = 0"));
        assert!(has_code_signal("compute(1)"));
        assert!(has_code_signal("Foo::Bar"));
        assert!(has_code_signal("a -> b"));
        // A space before the bracket is what prose does.
        assert!(!has_code_signal("Returns the total (in cents)"));
        assert!(!has_code_signal("See the README for details"));
    }

    #[test]
    fn a_bare_word_is_not_commented_out_code() {
        // The punctuation pre-gate and the statement guard both stop it.
        assert!(!looks_like_code("ruby", &s(&["rescue"])));
        assert!(!looks_like_code("ruby", &s(&["total"])));
    }
}
