//! `kb tools` — Claude-prompt-friendly manifest of every CLI verb.
//!
//! Walks the clap `Command` tree at runtime so the manifest never
//! drifts from the binary. Output format: one markdown section per
//! subcommand (`## kb <name>`) with synopsis + description + a curated
//! example invocation. Drop the output into a Claude system prompt to
//! teach the model the surface in one paste.

use anyhow::Result;
use clap::CommandFactory;

/// Shown above `kb --help`: the ten verbs a first-time user (or their
/// agent) needs. Everything else is in the full list below it.
pub const START_HERE: &str = "Start here:\n  \
kb daemon       start the daemon (kb add <dir> first registers a folder)\n  \
kb add          register a source folder as a kb\n  \
kb search       find artifacts (all kbs by default when the daemon serves several)\n  \
kb read         open an artifact in the browser\n  \
kb remember     store a memory\n  \
kb recall       recall memories relevant to a query\n  \
kb why          why is this file the way it is (past sessions)\n  \
kb recollect    has something like this been done before\n  \
kb comments     read and answer review comments\n  \
kb slate        this project's shared working state\n\n  \
`kb tools --core` prints a short manifest of these for an agent instruction file.";

/// The verbs `kb tools --core` documents, in display order.
pub const CORE_VERBS: [&str; 10] = [
    "daemon",
    "add",
    "search",
    "read",
    "remember",
    "recall",
    "why",
    "recollect",
    "comments",
    "slate",
];

/// Hard size budget for the core manifest (bytes) — it is meant to be
/// pasted into foreign-harness instruction files.
pub const CORE_MAX_BYTES: usize = 8 * 1024;

pub fn run(core: bool) -> Result<()> {
    if core {
        print!("{}", core_manifest());
    } else {
        print!("{}", render());
    }
    Ok(())
}

/// The whole manifest as text - what `kb tools` prints, byte for byte.
fn render() -> String {
    let cli = crate::Cli::command();
    let mut out = String::from("# kb CLI surface\n\n");
    out.push_str(
        "Generated by `kb tools`. Walks clap's Command tree so the manifest \
         matches the binary. Drop into a Claude system prompt to teach the \
         model how to drive kb without reading docs.\n\n",
    );
    for sub in cli.get_subcommands() {
        emit(&mut out, sub, "kb");
    }
    out
}

/// First sentence of a command's about text, capped, single line.
fn first_sentence(cmd: &clap::Command) -> String {
    let about = cmd.get_about().map(|a| a.to_string()).unwrap_or_default();
    let flat = about.split_whitespace().collect::<Vec<_>>().join(" ");
    let end = flat
        .find(". ")
        .map(|i| i + 1)
        .unwrap_or(flat.len())
        .min(200);
    let mut cut = end;
    while !flat.is_char_boundary(cut) {
        cut -= 1;
    }
    flat[..cut].to_string()
}

/// The `kb tools --core` manifest: the ten core verbs only, one
/// sentence + one synopsis (subcommands named, not expanded) + one
/// example each. Derived from the clap tree, so it cannot drift.
pub fn core_manifest() -> String {
    let cli = crate::Cli::command();
    let mut out = String::from(
        "# kb core verbs\n\nGenerated by `kb tools --core`. Run `kb tools` for every verb, \
         `kb <verb> --help` for flags.\n\n",
    );
    for name in CORE_VERBS {
        let Some(sub) = cli.get_subcommands().find(|c| c.get_name() == name) else {
            continue;
        };
        let qualified = format!("kb {name}");
        out.push_str(&format!("## {qualified}\n\n{}\n\n", first_sentence(sub)));
        let mut syn = synopsis(sub, &qualified);
        if sub.has_subcommands() {
            let names: Vec<&str> = sub.get_subcommands().map(|c| c.get_name()).collect();
            syn = syn.replace(" <SUBCOMMAND>", &format!(" {{{}}}", names.join("|")));
        }
        out.push_str(&format!("```\n{syn}\n```\n\n"));
        if let Some(example) = example_for(name) {
            out.push_str(&format!("Example:\n```\n{example}\n```\n\n"));
        }
    }
    debug_assert!(out.len() <= CORE_MAX_BYTES, "core manifest over budget");
    out
}

fn emit(out: &mut String, cmd: &clap::Command, parent: &str) {
    let name = cmd.get_name();
    let qualified = format!("{parent} {name}");
    out.push_str(&format!("## {qualified}\n\n"));
    if let Some(about) = cmd.get_about() {
        out.push_str(&format!("{about}\n\n"));
    }
    let synopsis = synopsis(cmd, &qualified);
    out.push_str(&format!("```\n{synopsis}\n```\n\n"));
    if let Some(example) = example_for(name) {
        out.push_str(&format!("Example:\n```\n{example}\n```\n\n"));
    }
    for sub in cmd.get_subcommands() {
        emit(out, sub, &qualified);
    }
}

/// Render a one-line synopsis: `kb foo <POS> [--flag VAL]`. Args
/// preserve clap's required/optional display.
fn synopsis(cmd: &clap::Command, qualified: &str) -> String {
    let mut out = qualified.to_string();
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        let id = arg.get_id().as_str();
        if id == "help" || id == "version" {
            continue;
        }
        let fragment = if arg.is_positional() {
            if arg.is_required_set() {
                format!(" <{}>", id.to_uppercase())
            } else {
                format!(" [{}]", id.to_uppercase())
            }
        } else {
            // Long-flag form. Skip short for clarity in the manifest.
            let long = arg
                .get_long()
                .map(|l| format!("--{l}"))
                .unwrap_or_else(|| format!("--{id}"));
            let takes_value = arg.get_action().takes_values();
            if takes_value {
                format!(" [{long} VALUE]")
            } else {
                format!(" [{long}]")
            }
        };
        out.push_str(&fragment);
    }
    if cmd.has_subcommands() {
        out.push_str(" <SUBCOMMAND>");
    }
    out
}

/// Curated examples per subcommand. Skip when the verb's synopsis is
/// self-explanatory (status, list, etc.). Keep these short — Claude's
/// context window is finite.
fn example_for(name: &str) -> Option<&'static str> {
    match name {
        "search" => Some("kb search 'borrow checker' --kb canon --json"),
        "get" => Some("kb get abc123def456 --kb canon --format json"),
        "reading" => Some("kb reading kb-feature-roadmap.html --kb canon --json   # what the user read / skimmed / stopped at"),
        "related" => Some("kb related abc123def456 --kb canon --depth 2"),
        "comments" => Some(
            "kb comments add canon abc123def456 --body 'Pin section needs an example' --author claude\n\
             kb comments list --kb canon --json\n\
             kb comments resolve canon abc123def456 c_xxxx",
        ),
        "atlas" => Some("kb atlas recompute --kb canon"),
        "exclude" => Some(
            "kb exclude flaky-viz.html --kb canon --note 'broken generator'\n\
             kb exclude --list --kb canon\n\
             kb exclude flaky-viz.html --rm --kb canon",
        ),
        "push" => Some("kb push --filter artifact.indexed --filter comment.anchor_stale | claude code -- 'react to kb events'"),
        "pull" => Some(
            "kb pull --from https://kb.example.com --kb kb-docs --into /srv/kb-docs \\\n\
             \x20 --oidc-token-url https://auth.example.com/api/oidc/token --oidc-client-id kb-bot\n\
             # KB_OIDC_CLIENT_SECRET supplied via the environment",
        ),
        "token" => Some(
            "kb token generate    # writes ~/.config/kb/token mode 0600\n\
             TOKEN=$(kb token show --print)\n\
             kb token issue alice    # appends alice:sha256:<hex> to <config>/tokens\n\
             kb token revoke alice",
        ),
        "whoami" => Some("kb whoami\nkb whoami --output json"),
        "users" => Some("kb users\nkb users --output json"),
        "history" => Some("kb history --kb canon --user alice --limit 20"),
        "model" => Some("kb model list\nkb model set bge-small-en-v1.5 --kb canon --in-place"),
        "refs" => Some(
            "kb refs kitchen-sink.html --kb canon --json\n\
             kb refs --kb canon --lint          # whole corpus: what should be declared",
        ),
        "links" => Some(
            "kb links suggest --kb notes --limit 20     # unlinked mentions (derived, nothing stored)\n\
             kb links apply ops/runbook.md ops/deploy.md --kb notes   # author one [[wikilink]]",
        ),
        "slate" => Some(
            "kb slate open                                   # read FIRST; re-run after /compact\n\
             kb slate take crates/kb-server 'A2 bearer graduation'   # exit 3 = a live session has it\n\
             kb slate found 'auth ends at the gate' --ref path:crates/kb-server/src/review_gate.rs:88\n\
             kb slate ask 'does refuse_if_volume_ahead run before migrations?'\n\
             kb slate tried 'e2e + cargo concurrently' --failed 'OOM at the 10g cgroup'\n\
             kb slate drop 41 'no longer in play'   # your own freely; another live session's with --anyway\n\
             kb slate delta --json                  # what changed since your cursor",
        ),
        "desk" => Some(
            "kb desk offer draft.md --as ticket-123 --ttl 24h\n\
             kb desk wait --path handoff/ticket-123.md --once --timeout 900\n\
             kb desk ls --all                                          # fleet-wide, * = attention\n\
             kb desk promote ticket-123 --to notes/ticket-123.md --category note",
        ),
        "chores" => Some(
            "kb chores                 # what agent-layer upkeep is due, and which skill runs it\n\
             kb chores --json          # {due:[{id,skill,reason}], unavailable:[...]}\n\
             kb chores --line          # one counts-only line, once per UTC day, silent when nothing is due",
        ),
        "outbox" => Some(
            "kb outbox list            # `kb remember` writes spooled while the daemon was slow or down\n\
             kb outbox flush           # replay them now (the daemon dedupes on client_ref)",
        ),
        "rescrub" => Some(
            "kb sessions rescrub                  # dry run: per-lane count of captures still holding a secret\n\
             kb sessions rescrub --apply         # rewrite only the affected captures, atomically",
        ),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    /// Every example for the upkeep verbs must name a real verb path with
    /// real flags: a doc line that does not parse is a lie the manifest
    /// would hand a model.
    #[test]
    fn upkeep_examples_parse_against_the_real_cli() {
        for name in ["chores", "outbox", "rescrub"] {
            let ex = example_for(name).unwrap_or_else(|| panic!("no example for {name}"));
            for line in ex.lines() {
                let cmd = line.split('#').next().unwrap().trim();
                let argv: Vec<&str> = cmd.split_whitespace().collect();
                assert_eq!(argv[0], "kb", "{line}");
                if let Err(e) = crate::Cli::command().try_get_matches_from(argv) {
                    panic!("`{cmd}` does not parse: {e}");
                }
            }
        }
    }

    /// Exercises the EMITTED text (not just the clap tree): each upkeep verb
    /// has its own section, its synopsis block and its example block.
    #[test]
    fn the_manifest_emits_the_upkeep_verbs() {
        let text = render();
        assert!(text.starts_with("# kb CLI surface\n\n"));
        for (heading, name) in [
            ("## kb chores\n", "chores"),
            ("## kb outbox\n", "outbox"),
            ("## kb sessions rescrub\n", "rescrub"),
        ] {
            let start = text
                .find(heading)
                .unwrap_or_else(|| panic!("{heading:?} missing from the emitted manifest"));
            let section = &text[start..];
            let section = section[heading.len()..]
                .split("\n## ")
                .next()
                .unwrap_or_default();
            assert!(
                section.contains(&format!(
                    "```\n{}",
                    heading.trim_start_matches("## ").trim()
                )),
                "{heading:?}: no synopsis block starting at the qualified verb"
            );
            let example = example_for(name).unwrap();
            assert!(
                section.contains(&format!("Example:\n```\n{example}\n```")),
                "{heading:?}: the example is not in the emitted section"
            );
        }
    }

    #[test]
    fn core_manifest_fits_the_budget_and_names_every_core_verb() {
        let m = core_manifest();
        assert!(
            m.len() <= CORE_MAX_BYTES,
            "core manifest is {} bytes (budget {CORE_MAX_BYTES})",
            m.len()
        );
        for v in CORE_VERBS {
            assert!(m.contains(&format!("## kb {v}\n")), "missing {v}");
        }
        // Not the full surface.
        assert!(!m.contains("## kb reindex"));
    }

    #[test]
    fn core_verbs_all_exist_in_the_clap_tree() {
        let cli = crate::Cli::command();
        for v in CORE_VERBS {
            assert!(
                cli.get_subcommands().any(|c| c.get_name() == v),
                "core verb {v} is not a subcommand"
            );
        }
    }

    /// The first phase-ID-shaped token in `text`, if any: a whole
    /// alphanumeric run of 1-3 capitals then digits (`R0`, `SL3`, `W4`), a
    /// `-X9` suffix form (`CT-C3` is caught by its `C3` run), `Proposal N`,
    /// `Wave N`, or a `v0.N` release tag. Legit acronyms with digits are
    /// allow-listed by name.
    fn phase_id_in(text: &str) -> Option<String> {
        const ALLOW: &[&str] = &[
            "BM25", "SHA1", "SHA256", "SHA512", "UTF8", "MD5", "IPV4", "IPV6",
        ];
        let bytes = text.as_bytes();
        let mut i = 0;
        while i < bytes.len() {
            if bytes[i].is_ascii_alphanumeric() {
                let start = i;
                while i < bytes.len() && bytes[i].is_ascii_alphanumeric() {
                    i += 1;
                }
                let run = &text[start..i];
                let caps = run.bytes().take_while(|b| b.is_ascii_uppercase()).count();
                let rest = &run[caps..];
                if (1..=3).contains(&caps)
                    && !rest.is_empty()
                    && rest.bytes().all(|b| b.is_ascii_digit())
                    && !ALLOW.contains(&run)
                {
                    return Some(run.to_string());
                }
                if run == "v0" && text[i..].starts_with('.') {
                    return Some(format!(
                        "v0{}",
                        text[i..].chars().take(3).collect::<String>()
                    ));
                }
                if (run == "Proposal" || run == "Wave")
                    && text[i..]
                        .trim_start_matches([' ', '-'])
                        .starts_with(|c: char| c.is_ascii_digit())
                {
                    return Some(format!("{run} N"));
                }
            } else {
                i += 1;
            }
        }
        None
    }

    #[test]
    fn phase_id_detector_flags_the_shapes_and_spares_acronyms() {
        for bad in [
            "R0",
            "SL3",
            "W4/W3.A",
            "CT-C3",
            "v0.44",
            "Proposal 2",
            "Wave 0",
            "(D26)",
        ] {
            assert!(phase_id_in(bad).is_some(), "{bad} should be flagged");
        }
        for ok in [
            "BM25 + vector",
            "SHA256",
            "plain prose",
            "R",
            "ascii",
            "x86",
            "k=60",
        ] {
            assert!(phase_id_in(ok).is_none(), "{ok} should pass");
        }
    }

    /// Walk the WHOLE rendered help tree (every command's about/long_about
    /// and every argument's help/long_help), not a hand-picked list of
    /// banned strings: provenance belongs in an adjacent `// Provenance:`
    /// source comment, never in what an operator reads in `--help`.
    #[test]
    fn whole_help_tree_has_no_phase_ids() {
        fn walk(cmd: &clap::Command, path: &str, bad: &mut Vec<String>) {
            let mut texts: Vec<(String, String)> = Vec::new();
            for t in [cmd.get_about(), cmd.get_long_about()]
                .into_iter()
                .flatten()
            {
                texts.push((format!("`{path}` about"), t.to_string()));
            }
            for a in cmd.get_arguments() {
                for t in [a.get_help(), a.get_long_help()].into_iter().flatten() {
                    texts.push((format!("`{path} --{}`", a.get_id()), t.to_string()));
                }
            }
            for (where_, text) in texts {
                if let Some(hit) = phase_id_in(&text) {
                    bad.push(format!(
                        "{where_} leaks `{hit}`: {}",
                        text.lines().next().unwrap_or("")
                    ));
                }
            }
            for sub in cmd.get_subcommands() {
                walk(sub, &format!("{path} {}", sub.get_name()), bad);
            }
        }
        let mut bad = Vec::new();
        walk(&crate::Cli::command(), "kb", &mut bad);
        assert!(bad.is_empty(), "phase IDs in --help:\n{}", bad.join("\n"));
    }

    #[test]
    fn top_level_help_has_start_here() {
        let cli = crate::Cli::command();
        let help = cli.clone().render_help().to_string();
        assert!(help.contains("Start here:"), "{help}");
    }
}
