//! `kb tools` — Claude-prompt-friendly manifest of every CLI verb.
//!
//! Walks the clap `Command` tree at runtime so the manifest never
//! drifts from the binary. Output format: one markdown section per
//! subcommand (`## kb <name>`) with synopsis + description + a curated
//! example invocation. Drop the output into a Claude system prompt to
//! teach the model the surface in one paste.

use anyhow::Result;
use clap::CommandFactory;

pub fn run() -> Result<()> {
    print!("{}", render());
    Ok(())
}

/// The whole manifest as text - what `kb tools` prints, byte for byte.
fn render() -> String {
    let cli = crate::Cli::command();
    let mut out = String::from("# kb CLI surface\n\n");
    out.push_str(
        "Generated by `kb tools`. Walks clap's Command tree so the manifest \
         matches the binary. Drop into a Claude system prompt to teach the \
         model how to drive kb without reading docs.\n\n",
    );
    for sub in cli.get_subcommands() {
        emit(&mut out, sub, "kb");
    }
    out
}

fn emit(out: &mut String, cmd: &clap::Command, parent: &str) {
    let name = cmd.get_name();
    let qualified = format!("{parent} {name}");
    out.push_str(&format!("## {qualified}\n\n"));
    if let Some(about) = cmd.get_about() {
        out.push_str(&format!("{about}\n\n"));
    }
    let synopsis = synopsis(cmd, &qualified);
    out.push_str(&format!("```\n{synopsis}\n```\n\n"));
    if let Some(example) = example_for(name) {
        out.push_str(&format!("Example:\n```\n{example}\n```\n\n"));
    }
    for sub in cmd.get_subcommands() {
        emit(out, sub, &qualified);
    }
}

/// Render a one-line synopsis: `kb foo <POS> [--flag VAL]`. Args
/// preserve clap's required/optional display.
fn synopsis(cmd: &clap::Command, qualified: &str) -> String {
    let mut out = qualified.to_string();
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        let id = arg.get_id().as_str();
        if id == "help" || id == "version" {
            continue;
        }
        let fragment = if arg.is_positional() {
            if arg.is_required_set() {
                format!(" <{}>", id.to_uppercase())
            } else {
                format!(" [{}]", id.to_uppercase())
            }
        } else {
            // Long-flag form. Skip short for clarity in the manifest.
            let long = arg
                .get_long()
                .map(|l| format!("--{l}"))
                .unwrap_or_else(|| format!("--{id}"));
            let takes_value = arg.get_action().takes_values();
            if takes_value {
                format!(" [{long} VALUE]")
            } else {
                format!(" [{long}]")
            }
        };
        out.push_str(&fragment);
    }
    if cmd.has_subcommands() {
        out.push_str(" <SUBCOMMAND>");
    }
    out
}

/// Curated examples per subcommand. Skip when the verb's synopsis is
/// self-explanatory (status, list, etc.). Keep these short — Claude's
/// context window is finite.
fn example_for(name: &str) -> Option<&'static str> {
    match name {
        "search" => Some("kb search 'borrow checker' --kb canon --json"),
        "get" => Some("kb get abc123def456 --kb canon --format json"),
        "reading" => Some("kb reading kb-feature-roadmap.html --kb canon --json   # what the user read / skimmed / stopped at"),
        "related" => Some("kb related abc123def456 --kb canon --depth 2"),
        "comments" => Some(
            "kb comments add canon abc123def456 --body 'Pin section needs an example' --author claude\n\
             kb comments list --kb canon --json\n\
             kb comments resolve canon abc123def456 c_xxxx",
        ),
        "atlas" => Some("kb atlas recompute --kb canon"),
        "exclude" => Some(
            "kb exclude flaky-viz.html --kb canon --note 'broken generator'\n\
             kb exclude --list --kb canon\n\
             kb exclude flaky-viz.html --rm --kb canon",
        ),
        "push" => Some("kb push --filter artifact.indexed --filter comment.anchor_stale | claude code -- 'react to kb events'"),
        "pull" => Some(
            "kb pull --from https://kb.example.com --kb kb-docs --into /srv/kb-docs \\\n\
             \x20 --oidc-token-url https://auth.example.com/api/oidc/token --oidc-client-id kb-bot\n\
             # KB_OIDC_CLIENT_SECRET supplied via the environment",
        ),
        "token" => Some(
            "kb token generate    # writes ~/.config/kb/token mode 0600\n\
             TOKEN=$(kb token show --print)\n\
             kb token issue alice    # appends alice:sha256:<hex> to <config>/tokens\n\
             kb token revoke alice",
        ),
        "whoami" => Some("kb whoami\nkb whoami --output json"),
        "users" => Some("kb users\nkb users --output json"),
        "history" => Some("kb history --kb canon --user alice --limit 20"),
        "model" => Some("kb model list\nkb model set bge-small-en-v1.5 --kb canon --in-place"),
        "refs" => Some(
            "kb refs kitchen-sink.html --kb canon --json\n\
             kb refs --kb canon --lint          # whole corpus: what should be declared",
        ),
        "links" => Some(
            "kb links suggest --kb notes --limit 20     # unlinked mentions (derived, nothing stored)\n\
             kb links apply ops/runbook.md ops/deploy.md --kb notes   # author one [[wikilink]]",
        ),
        "slate" => Some(
            "kb slate open                                   # read FIRST; re-run after /compact\n\
             kb slate take crates/kb-server 'A2 bearer graduation'   # exit 3 = a live session has it\n\
             kb slate found 'auth ends at the gate' --ref path:crates/kb-server/src/review_gate.rs:88\n\
             kb slate ask 'does refuse_if_volume_ahead run before migrations?'\n\
             kb slate tried 'e2e + cargo concurrently' --failed 'OOM at the 10g cgroup'\n\
             kb slate drop 41 'no longer in play'   # your own freely; another live session's with --anyway\n\
             kb slate delta --json                  # what changed since your cursor",
        ),
        "desk" => Some(
            "kb desk offer draft.md --as ticket-123 --ttl 24h\n\
             kb desk wait --path handoff/ticket-123.md --once --timeout 900\n\
             kb desk ls --all                                          # fleet-wide, * = attention\n\
             kb desk promote ticket-123 --to notes/ticket-123.md --category note",
        ),
        "chores" => Some(
            "kb chores                 # what agent-layer upkeep is due, and which skill runs it\n\
             kb chores --json          # {due:[{id,skill,reason}], unavailable:[...]}\n\
             kb chores --line          # one counts-only line, once per UTC day, silent when nothing is due",
        ),
        "outbox" => Some(
            "kb outbox list            # `kb remember` writes spooled while the daemon was slow or down\n\
             kb outbox flush           # replay them now (the daemon dedupes on client_ref)",
        ),
        "rescrub" => Some(
            "kb sessions rescrub                  # dry run: per-lane count of captures still holding a secret\n\
             kb sessions rescrub --apply         # rewrite only the affected captures, atomically",
        ),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    /// Every example for the upkeep verbs must name a real verb path with
    /// real flags: a doc line that does not parse is a lie the manifest
    /// would hand a model.
    #[test]
    fn upkeep_examples_parse_against_the_real_cli() {
        for name in ["chores", "outbox", "rescrub"] {
            let ex = example_for(name).unwrap_or_else(|| panic!("no example for {name}"));
            for line in ex.lines() {
                let cmd = line.split('#').next().unwrap().trim();
                let argv: Vec<&str> = cmd.split_whitespace().collect();
                assert_eq!(argv[0], "kb", "{line}");
                if let Err(e) = crate::Cli::command().try_get_matches_from(argv) {
                    panic!("`{cmd}` does not parse: {e}");
                }
            }
        }
    }

    /// Exercises the EMITTED text (not just the clap tree): each upkeep verb
    /// has its own section, its synopsis block and its example block.
    #[test]
    fn the_manifest_emits_the_upkeep_verbs() {
        let text = render();
        assert!(text.starts_with("# kb CLI surface\n\n"));
        for (heading, name) in [
            ("## kb chores\n", "chores"),
            ("## kb outbox\n", "outbox"),
            ("## kb sessions rescrub\n", "rescrub"),
        ] {
            let start = text
                .find(heading)
                .unwrap_or_else(|| panic!("{heading:?} missing from the emitted manifest"));
            let section = &text[start..];
            let section = section[heading.len()..]
                .split("\n## ")
                .next()
                .unwrap_or_default();
            assert!(
                section.contains(&format!(
                    "```\n{}",
                    heading.trim_start_matches("## ").trim()
                )),
                "{heading:?}: no synopsis block starting at the qualified verb"
            );
            let example = example_for(name).unwrap();
            assert!(
                section.contains(&format!("Example:\n```\n{example}\n```")),
                "{heading:?}: the example is not in the emitted section"
            );
        }
    }
}
