//! `kb tools` — Claude-prompt-friendly manifest of every CLI verb.
//!
//! Walks the clap `Command` tree at runtime so the manifest never
//! drifts from the binary. Output format: one markdown section per
//! subcommand (`## kb <name>`) with synopsis + description + a curated
//! example invocation. Drop the output into a Claude system prompt to
//! teach the model the surface in one paste.

use anyhow::Result;
use clap::CommandFactory;

/// Shown above `kb --help`: the ten verbs a first-time user (or their
/// agent) needs. Everything else is in the full list below it.
pub const START_HERE: &str = "Start here:\n  \
kb daemon       start the daemon (kb add <dir> first registers a folder)\n  \
kb add          register a source folder as a kb\n  \
kb search       find artifacts (all kbs by default when the daemon serves several)\n  \
kb read         open an artifact in the browser\n  \
kb remember     store a memory\n  \
kb recall       recall memories relevant to a query\n  \
kb why          why is this file the way it is (past sessions)\n  \
kb recollect    has something like this been done before\n  \
kb comments     read and answer review comments\n  \
kb slate        this project's shared working state\n\n  \
`kb tools --core` prints a short manifest of these for an agent instruction file.";

/// The verbs `kb tools --core` documents, in display order.
pub const CORE_VERBS: [&str; 10] = [
    "daemon",
    "add",
    "search",
    "read",
    "remember",
    "recall",
    "why",
    "recollect",
    "comments",
    "slate",
];

/// Hard size budget for the core manifest (bytes) — it is meant to be
/// pasted into foreign-harness instruction files.
pub const CORE_MAX_BYTES: usize = 8 * 1024;

pub fn run(core: bool) -> Result<()> {
    if core {
        print!("{}", core_manifest());
        return Ok(());
    }
    let cli = crate::Cli::command();
    println!("# kb CLI surface\n");
    println!(
        "Generated by `kb tools`. Walks clap's Command tree so the manifest \
         matches the binary. Drop into a Claude system prompt to teach the \
         model how to drive kb without reading docs.\n"
    );
    for sub in cli.get_subcommands() {
        emit(sub, "kb");
    }
    Ok(())
}

/// First sentence of a command's about text, capped, single line.
fn first_sentence(cmd: &clap::Command) -> String {
    let about = cmd.get_about().map(|a| a.to_string()).unwrap_or_default();
    let flat = about.split_whitespace().collect::<Vec<_>>().join(" ");
    let end = flat
        .find(". ")
        .map(|i| i + 1)
        .unwrap_or(flat.len())
        .min(200);
    let mut cut = end;
    while !flat.is_char_boundary(cut) {
        cut -= 1;
    }
    flat[..cut].to_string()
}

/// The `kb tools --core` manifest: the ten core verbs only, one
/// sentence + one synopsis (subcommands named, not expanded) + one
/// example each. Derived from the clap tree, so it cannot drift.
pub fn core_manifest() -> String {
    let cli = crate::Cli::command();
    let mut out = String::from(
        "# kb core verbs\n\nGenerated by `kb tools --core`. Run `kb tools` for every verb, \
         `kb <verb> --help` for flags.\n\n",
    );
    for name in CORE_VERBS {
        let Some(sub) = cli.get_subcommands().find(|c| c.get_name() == name) else {
            continue;
        };
        let qualified = format!("kb {name}");
        out.push_str(&format!("## {qualified}\n\n{}\n\n", first_sentence(sub)));
        let mut syn = synopsis(sub, &qualified);
        if sub.has_subcommands() {
            let names: Vec<&str> = sub.get_subcommands().map(|c| c.get_name()).collect();
            syn = syn.replace(" <SUBCOMMAND>", &format!(" {{{}}}", names.join("|")));
        }
        out.push_str(&format!("```\n{syn}\n```\n\n"));
        if let Some(example) = example_for(name) {
            out.push_str(&format!("Example:\n```\n{example}\n```\n\n"));
        }
    }
    debug_assert!(out.len() <= CORE_MAX_BYTES, "core manifest over budget");
    out
}

fn emit(cmd: &clap::Command, parent: &str) {
    let name = cmd.get_name();
    let qualified = format!("{parent} {name}");
    println!("## {qualified}\n");
    if let Some(about) = cmd.get_about() {
        println!("{about}\n");
    }
    let synopsis = synopsis(cmd, &qualified);
    println!("```\n{synopsis}\n```\n");
    if let Some(example) = example_for(name) {
        println!("Example:\n```\n{example}\n```\n");
    }
    for sub in cmd.get_subcommands() {
        emit(sub, &qualified);
    }
}

/// Render a one-line synopsis: `kb foo <POS> [--flag VAL]`. Args
/// preserve clap's required/optional display.
fn synopsis(cmd: &clap::Command, qualified: &str) -> String {
    let mut out = qualified.to_string();
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        let id = arg.get_id().as_str();
        if id == "help" || id == "version" {
            continue;
        }
        let fragment = if arg.is_positional() {
            if arg.is_required_set() {
                format!(" <{}>", id.to_uppercase())
            } else {
                format!(" [{}]", id.to_uppercase())
            }
        } else {
            // Long-flag form. Skip short for clarity in the manifest.
            let long = arg
                .get_long()
                .map(|l| format!("--{l}"))
                .unwrap_or_else(|| format!("--{id}"));
            let takes_value = arg.get_action().takes_values();
            if takes_value {
                format!(" [{long} VALUE]")
            } else {
                format!(" [{long}]")
            }
        };
        out.push_str(&fragment);
    }
    if cmd.has_subcommands() {
        out.push_str(" <SUBCOMMAND>");
    }
    out
}

/// Curated examples per subcommand. Skip when the verb's synopsis is
/// self-explanatory (status, list, etc.). Keep these short — Claude's
/// context window is finite.
fn example_for(name: &str) -> Option<&'static str> {
    match name {
        "search" => Some("kb search 'borrow checker' --kb canon --json"),
        "get" => Some("kb get abc123def456 --kb canon --format json"),
        "reading" => Some("kb reading kb-feature-roadmap.html --kb canon --json   # what the user read / skimmed / stopped at"),
        "related" => Some("kb related abc123def456 --kb canon --depth 2"),
        "comments" => Some(
            "kb comments add canon abc123def456 --body 'Pin section needs an example' --author claude\n\
             kb comments list --kb canon --json\n\
             kb comments resolve canon abc123def456 c_xxxx",
        ),
        "atlas" => Some("kb atlas recompute --kb canon"),
        "exclude" => Some(
            "kb exclude flaky-viz.html --kb canon --note 'broken generator'\n\
             kb exclude --list --kb canon\n\
             kb exclude flaky-viz.html --rm --kb canon",
        ),
        "push" => Some("kb push --filter artifact.indexed --filter comment.anchor_stale | claude code -- 'react to kb events'"),
        "pull" => Some(
            "kb pull --from https://kb.example.com --kb kb-docs --into /srv/kb-docs \\\n\
             \x20 --oidc-token-url https://auth.example.com/api/oidc/token --oidc-client-id kb-bot\n\
             # KB_OIDC_CLIENT_SECRET supplied via the environment",
        ),
        "token" => Some(
            "kb token generate    # writes ~/.config/kb/token mode 0600\n\
             TOKEN=$(kb token show --print)\n\
             kb token issue alice    # appends alice:sha256:<hex> to <config>/tokens\n\
             kb token revoke alice",
        ),
        "whoami" => Some("kb whoami\nkb whoami --output json"),
        "users" => Some("kb users\nkb users --output json"),
        "history" => Some("kb history --kb canon --user alice --limit 20"),
        "model" => Some("kb model list\nkb model set bge-small-en-v1.5 --kb canon --in-place"),
        "refs" => Some(
            "kb refs kitchen-sink.html --kb canon --json\n\
             kb refs --kb canon --lint          # whole corpus: what should be declared",
        ),
        "links" => Some(
            "kb links suggest --kb notes --limit 20     # unlinked mentions (derived, nothing stored)\n\
             kb links apply ops/runbook.md ops/deploy.md --kb notes   # author one [[wikilink]]",
        ),
        "slate" => Some(
            "kb slate open                                   # read FIRST; re-run after /compact\n\
             kb slate take crates/kb-server 'A2 bearer graduation'   # exit 3 = a live session has it\n\
             kb slate found 'auth ends at the gate' --ref path:crates/kb-server/src/review_gate.rs:88\n\
             kb slate ask 'does refuse_if_volume_ahead run before migrations?'\n\
             kb slate tried 'e2e + cargo concurrently' --failed 'OOM at the 10g cgroup'\n\
             kb slate drop 41 'no longer in play'   # your own freely; another live session's with --anyway\n\
             kb slate delta --json                  # what changed since your cursor",
        ),
        "desk" => Some(
            "kb desk offer draft.md --as ticket-123 --ttl 24h\n\
             kb desk wait --path handoff/ticket-123.md --once --timeout 900\n\
             kb desk ls --all                                          # fleet-wide, * = attention\n\
             kb desk promote ticket-123 --to notes/ticket-123.md --category note",
        ),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn core_manifest_fits_the_budget_and_names_every_core_verb() {
        let m = core_manifest();
        assert!(
            m.len() <= CORE_MAX_BYTES,
            "core manifest is {} bytes (budget {CORE_MAX_BYTES})",
            m.len()
        );
        for v in CORE_VERBS {
            assert!(m.contains(&format!("## kb {v}\n")), "missing {v}");
        }
        // Not the full surface.
        assert!(!m.contains("## kb reindex"));
    }

    #[test]
    fn core_verbs_all_exist_in_the_clap_tree() {
        let cli = crate::Cli::command();
        for v in CORE_VERBS {
            assert!(
                cli.get_subcommands().any(|c| c.get_name() == v),
                "core verb {v} is not a subcommand"
            );
        }
    }

    #[test]
    fn top_level_help_has_start_here_and_no_phase_ids() {
        let cli = crate::Cli::command();
        let help = cli.clone().render_help().to_string();
        assert!(help.contains("Start here:"), "{help}");
        // Phase-ID shapes that used to lead the verb summaries.
        let banned = [
            "v0.", "CT-", "MI-W", "W2.", "GC-B", "TM-track", "M5 ", "SL3",
        ];
        for sub in cli.get_subcommands() {
            let about = sub.get_about().map(|a| a.to_string()).unwrap_or_default();
            let first = about.as_str();
            for b in banned {
                assert!(
                    !first.contains(b),
                    "`kb {}` summary leaks a phase ID ({b}): {first}",
                    sub.get_name()
                );
            }
        }
    }
}
