// V70-A5 — the kbc-cmd/1 → TypeScript generator (pure).
//
// `crates/kb-code-server/commands/registry.json` is the SOURCE. This module
// turns it into the checked-in `registry.gen.ts` the SPA imports. It is a
// separate module (not inlined into `scripts/gen-commands.mjs`) for exactly
// the reason `themes/derive.ts` is: the drift golden
// (`registry.gen.test.ts`) has to re-run the generator IN MEMORY and compare
// bytes, and vitest cannot import a `.mjs` script that writes files on
// import.
//
// Nothing here interprets a key. Emitting is a transliteration: the JSON's
// field order is preserved, unknown fields are dropped LOUDLY (a field the
// SPA does not model would otherwise rot silently), and every string is
// JSON-escaped rather than template-interpolated.

/// The raw shape of one `commands[]` row, straight off the JSON.
export interface RawCommand {
  id: string;
  title: string;
  aka: string[];
  group: string;
  keys: { vim: string[]; plain: string[]; helix: string[] };
  scope: string;
  when?: string;
  targets?: string[];
  cli: string;
  mutation: string;
  side_effect: string;
  affordance_anchor?: string;
  dismiss_order?: number;
  lifecycle: string;
  dispatch: string;
  vim_kind?: string;
  browser_reserved?: string;
  browser_passthrough?: boolean;
  note?: string;
  ratified_conflicts?: string[];
  owner?: string;
  retired_reason?: string;
}

export interface RawScope {
  id: string;
  title: string;
  depth: number;
  covers: string;
  coactive_with: string[];
}

export interface RawPreset {
  id: string;
  title: string;
  default: boolean;
  note: string;
}

export interface RawRegistry {
  schema: string;
  leader: string;
  note: string;
  presets: RawPreset[];
  reserved_chords: { note: string; hard: string[]; passthrough: string[] };
  context_keys: Array<{ key: string; values: string[]; note?: string }>;
  scopes: RawScope[];
  conflict_policy: string;
  commands: RawCommand[];
}

/// Every field of a command row this generator knows how to emit. A row
/// carrying anything else is a registry edit that never reached the SPA —
/// we throw rather than drop it, because a silently-ignored field is
/// precisely the drift this whole generated-copy dance exists to prevent.
const KNOWN_COMMAND_FIELDS = new Set([
  "id",
  "title",
  "aka",
  "group",
  "keys",
  "scope",
  "when",
  "targets",
  "cli",
  "mutation",
  "side_effect",
  "affordance_anchor",
  "dismiss_order",
  "lifecycle",
  "dispatch",
  "vim_kind",
  "browser_reserved",
  "browser_passthrough",
  "note",
  "ratified_conflicts",
  "owner",
  "retired_reason",
]);

function j(v: unknown): string {
  return JSON.stringify(v);
}

function emitCommand(c: RawCommand): string {
  for (const k of Object.keys(c)) {
    if (!KNOWN_COMMAND_FIELDS.has(k)) {
      throw new Error(
        `registry command ${c.id} carries unknown field ${JSON.stringify(k)} — teach ` +
          `web-code/src/commands/derive.ts about it (and the SPA type) before shipping the row`,
      );
    }
  }
  const out: string[] = [];
  out.push(`    id: ${j(c.id)},`);
  out.push(`    title: ${j(c.title)},`);
  out.push(`    aka: ${j(c.aka)},`);
  out.push(`    group: ${j(c.group)},`);
  out.push(
    `    keys: { vim: ${j(c.keys.vim)}, plain: ${j(c.keys.plain)}, helix: ${j(c.keys.helix)} },`,
  );
  out.push(`    scope: ${j(c.scope)},`);
  if (c.when !== undefined) out.push(`    when: ${j(c.when)},`);
  if (c.targets !== undefined) out.push(`    targets: ${j(c.targets)},`);
  out.push(`    cli: ${j(c.cli)},`);
  out.push(`    mutation: ${j(c.mutation)},`);
  out.push(`    sideEffect: ${j(c.side_effect)},`);
  if (c.affordance_anchor !== undefined) out.push(`    affordanceAnchor: ${j(c.affordance_anchor)},`);
  if (c.dismiss_order !== undefined) out.push(`    dismissOrder: ${c.dismiss_order},`);
  out.push(`    lifecycle: ${j(c.lifecycle)},`);
  out.push(`    dispatch: ${j(c.dispatch)},`);
  if (c.vim_kind !== undefined) out.push(`    vimKind: ${j(c.vim_kind)},`);
  if (c.browser_reserved !== undefined) out.push(`    browserReserved: ${j(c.browser_reserved)},`);
  if (c.browser_passthrough !== undefined) out.push(`    browserPassthrough: ${c.browser_passthrough},`);
  if (c.note !== undefined) out.push(`    note: ${j(c.note)},`);
  if (c.ratified_conflicts !== undefined)
    out.push(`    ratifiedConflicts: ${j(c.ratified_conflicts)},`);
  if (c.owner !== undefined) out.push(`    owner: ${j(c.owner)},`);
  if (c.retired_reason !== undefined) out.push(`    retiredReason: ${j(c.retired_reason)},`);
  return `  {\n${out.join("\n")}\n  },`;
}

export function generateRegistryTs(r: RawRegistry): string {
  const head = `// GENERATED by web-code/scripts/gen-commands.mjs from
// crates/kb-code-server/commands/registry.json — DO NOT EDIT BY HAND.
// Regenerate with \`npm run gen:commands\` in web-code/.
// The checked-in copy is pinned by src/commands/registry.gen.test.ts, which
// regenerates it in memory and asserts byte equality, so it cannot go stale.
//
// kbc-cmd/1 (v7 §P2): the ONE declaration home for kb-code's keyboard and
// command surface. A binding that is not in the registry does not exist —
// the \`?\` sheet, the palette, the which-key overlay and the printable
// cheatsheet all render from THESE rows.

export type KbcScope =
${r.scopes.map((s) => `  | ${j(s.id)}`).join("\n")};

export type KbcPreset = ${r.presets.map((p) => j(p.id)).join(" | ")};

/// \`none\` — reads only. \`metadata\` — writes a kb-code annotation/review row.
/// \`working-tree\` — touches the checkout. The palette routes anything other
/// than \`none\` through the one ConfirmProvider (root CLAUDE.md #32).
export type KbcMutation = "none" | "metadata" | "working-tree";

export type KbcSideEffect = "none" | "remote";

/// \`retired\` (V73-K6) — the row existed, describes a real key, but nothing
/// executes it anymore and nothing should: excluded from \`KBC_ACTIVE_COMMANDS\`
/// below (the palette, the \`?\` sheet, the which-key overlay and the
/// dispatcher all read that filtered list, never \`KBC_COMMANDS\` directly) —
/// \`KBC_COMMANDS\` itself keeps the row for the drift golden and the audit
/// trail. Distinct from \`planned\` (not built YET, still surfaced as
/// "planned" so the intent stays visible): a retired row is closed history,
/// invisible on purpose.
export type KbcLifecycle = "shipped" | "planned" | "retired";

/// Who fires the binding at the WINDOW layer. \`central\` — \`CommandRoot\`'s
/// single listener. \`surface\` — declared here for the sheet, the palette and
/// the conflicts gate, but a route/component-local handler (or the CM6 vim
/// layer) still owns execution. Inner layers always own themselves regardless;
/// this field describes the window-level host only. kb's own
/// \`web/src/lib/keymap.ts\` proved the shape.
export type KbcDispatch = "central" | "surface";

export interface KbcCommand {
  readonly id: string;
  readonly title: string;
  /// Extra words the palette's fuzzy matcher searches beside title and id.
  readonly aka: readonly string[];
  readonly group: string;
  readonly keys: {
    readonly vim: readonly string[];
    readonly plain: readonly string[];
    readonly helix: readonly string[];
  };
  readonly scope: KbcScope;
  /// A predicate over the context-key bag (see \`KBC_CONTEXT_KEYS\`), parsed by
  /// \`dispatch.ts\`'s \`evalWhen\`. Absent = always available in scope.
  readonly when?: string;
  readonly targets?: readonly string[];
  /// The CLI twin, or \`none:<reason>\`. \`kb-code commands doctor\` cross-joins
  /// the non-\`none\` values against the real clap tree, so a twin cannot be a
  /// stale string.
  readonly cli: string;
  readonly mutation: KbcMutation;
  readonly sideEffect: KbcSideEffect;
  /// The \`data-cmd\` id of the mouse affordance for this command — what the
  /// rehearsal overlay and learn mode address.
  readonly affordanceAnchor?: string;
  /// Esc class: lower dismisses first (innermost first). Esc NEVER navigates.
  readonly dismissOrder?: number;
  readonly lifecycle: KbcLifecycle;
  readonly dispatch: KbcDispatch;
  /// The \`VimCommand["t"]\` this row is executed as inside the CM6 buffer.
  readonly vimKind?: string;
  readonly browserReserved?: string;
  readonly browserPassthrough?: boolean;
  readonly note?: string;
  readonly ratifiedConflicts?: readonly string[];
  /// V73-K6 — the surface that claims a \`dispatch: "surface"\` row's
  /// execution when no \`useCommandHandlers\` registration names it and it
  /// carries no \`vimKind\` (the CM6 layer's own claim). Verified by
  /// \`commands/surfaceRows.test.ts\` against a fixed per-owner file set —
  /// see that file for the mechanism and \`web-code/CLAUDE.md\`'s keyboard
  /// section for the rule.
  readonly owner?: string;
  /// V73-K6 — present only when \`lifecycle === "retired"\`: why the row is
  /// no longer live.
  readonly retiredReason?: string;
}

export interface KbcScopeDef {
  readonly id: KbcScope;
  readonly title: string;
  /// Modal depth. A deeper scope shadows a shallower one BY DESIGN; two
  /// coactive scopes at the SAME depth binding one key is a conflict.
  readonly depth: number;
  readonly covers: string;
  readonly coactiveWith: readonly KbcScope[];
}

export interface KbcPresetDef {
  readonly id: KbcPreset;
  readonly title: string;
  readonly isDefault: boolean;
  readonly note: string;
}

export const KBC_CMD_SCHEMA = ${j(r.schema)};

export const KBC_LEADER = ${j(r.leader)};

export const KBC_PRESETS: readonly KbcPresetDef[] = [
${r.presets
  .map(
    (p) =>
      `  { id: ${j(p.id)}, title: ${j(p.title)}, isDefault: ${p.default}, note: ${j(p.note)} },`,
  )
  .join("\n")}
];

export const KBC_DEFAULT_PRESET: KbcPreset = ${j(
    (r.presets.find((p) => p.default) ?? r.presets[0]).id,
  )};

/// Chords the browser owns. \`hard\` can never be claimed; \`passthrough\` only
/// by a row that declares \`browserPassthrough\`.
export const KBC_RESERVED_CHORDS = {
  hard: ${j(r.reserved_chords.hard)} as readonly string[],
  passthrough: ${j(r.reserved_chords.passthrough)} as readonly string[],
};

export const KBC_CONTEXT_KEYS: readonly string[] = ${j(
    r.context_keys.map((c) => c.key),
  )};

export const KBC_SCOPES: readonly KbcScopeDef[] = [
${r.scopes
  .map(
    (s) =>
      `  { id: ${j(s.id)}, title: ${j(s.title)}, depth: ${s.depth}, covers: ${j(
        s.covers,
      )}, coactiveWith: ${j(s.coactive_with)} },`,
  )
  .join("\n")}
];

export const KBC_COMMANDS: readonly KbcCommand[] = [
${r.commands.map(emitCommand).join("\n")}
];

/// V73-K6 — \`KBC_COMMANDS\` minus \`lifecycle: "retired"\` rows: what "exists
/// right now" means to every LIVE consumer (the resolver, the palette, the
/// \`?\` sheet, the which-key overlay). \`KBC_COMMANDS\` stays the full,
/// byte-for-byte mirror of the registry — retired rows included — for the
/// drift golden (\`registry.gen.test.ts\`) and anything reading it as history.
export const KBC_ACTIVE_COMMANDS: readonly KbcCommand[] = KBC_COMMANDS.filter(
  (c) => c.lifecycle !== "retired",
);
`;
  return head;
}
