// Sample artifacts — technical / programming bias per spec example
const ARTIFACTS = [
  {
    id: 's01',
    title: 'Visualizing the Borrow Checker',
    summary: 'A full-screen interactive playground. Drag scopes, watch lifetimes resolve in real time. Built to live in a single window.',
    tags: ['rust', 'memory', 'ownership'],
    kb: 'work',
    age: '3h',
    mtime: 0,
    words: 240,
    backlinks: 6,
    outlinks: 2,
    indicators: { svg: 12, interactive: 1, code: 4, tables: 0, longread: 0 },
    accentTag: 'memory',
    realSrc: 'artifacts/fullscreen-viz.html',
    isNew: true,
  },
  {
    id: 's02',
    title: 'A Field Guide to Rust Errors',
    summary: 'Multi-page reference. Chapter 1: panics. Chapter 2: Result. Chapter 3: error trait. Chapter 4: best practices. Internal nav, no scrolling marathon.',
    tags: ['rust', 'errors'],
    kb: 'work',
    age: '1d',
    mtime: 1,
    words: 6800,
    backlinks: 14,
    outlinks: 22,
    indicators: { svg: 3, interactive: 1, code: 24, tables: 4, longread: 1 },
    accentTag: 'errors',
    realSrc: 'artifacts/multi-page.html',
    isNew: true,
  },
  {
    id: 's03',
    title: 'Everything HTML Can Do, in One Page',
    summary: 'A demonstration: <details>, dialogs, ranges, tables with sticky headers, copyable code, image galleries, math, popovers, drag-to-reorder, the works.',
    tags: ['rust', 'systems'],
    kb: 'work',
    age: '5h',
    mtime: 0,
    words: 3200,
    backlinks: 4,
    outlinks: 1,
    indicators: { svg: 8, interactive: 1, code: 18, tables: 6, longread: 1 },
    accentTag: 'systems',
    realSrc: 'artifacts/kitchen-sink.html',
    isNew: true,
  },
  {
    id: 's05',
    title: 'INC-0315 · Checkout Outage Postmortem',
    summary: 'Multi-file: a 5-page postmortem with summary, timeline, root-cause diagram, code diffs, and tracked action items. SEV-1, 47-minute outage caused by a string-vs-boolean coercion bug in flag bootstrap.',
    tags: ['systems', 'workflow'],
    kb: 'work',
    age: '1d',
    mtime: 1,
    words: 1800,
    backlinks: 5,
    outlinks: 2,
    indicators: { svg: 1, interactive: 0, code: 4, tables: 1, longread: 0 },
    accentTag: 'workflow',
    realSrc: 'artifacts/pm/00-summary.html',
    pages: [
      { label: 'Summary',     src: 'artifacts/pm/00-summary.html',  file: '00-summary.html'  },
      { label: 'Timeline',    src: 'artifacts/pm/01-timeline.html', file: '01-timeline.html' },
      { label: 'Root Cause',  src: 'artifacts/pm/02-cause.html',    file: '02-cause.html'    },
      { label: 'Action Items',src: 'artifacts/pm/03-actions.html',  file: '03-actions.html'  },
    ],
    isNew: true,
  },
  {
    id: 's04',
    title: 'The Cost of Abstraction',
    summary: 'A four-page essay with a chaptered index. A defense of writing it twice, against the long shadow of DRY. Cites and links into the Rust Errors field guide.',
    tags: ['systems', 'types'],
    kb: 'work',
    age: '6h',
    mtime: 0,
    words: 2400,
    backlinks: 3,
    outlinks: 4,
    indicators: { svg: 0, interactive: 0, code: 5, tables: 0, longread: 1 },
    accentTag: 'systems',
    realSrc: 'artifacts/cost-of-abstraction.html',
    isNew: true,
  },
  {
    id: 'a01',
    title: 'Async Error Handling Patterns',
    summary: 'Patterns for propagating errors across futures using ?, map_err, and bespoke types. The path from hand-written enums to thiserror, anyhow, and back again when you need typed errors at boundary code.',
    tags: ['rust', 'async', 'errors'],
    kb: 'work',
    age: '4d',
    mtime: 4,
    words: 2840,
    backlinks: 7,
    outlinks: 12,
    indicators: { svg: 0, interactive: 1, code: 14, tables: 2, longread: 1 },
    accentTag: 'rust',
  },
  {
    id: 'a02',
    title: 'Pin and Unpin, Demystified',
    summary: 'A visual model for self-referential structs and why Pin exists. Walks through the pinning contract, projection, and the dance between Pin<&mut T> and PhantomPinned.',
    tags: ['rust', 'async', 'pin'],
    kb: 'work',
    age: '6d',
    mtime: 6,
    words: 4120,
    backlinks: 11,
    outlinks: 8,
    indicators: { svg: 6, interactive: 1, code: 18, tables: 0, longread: 1 },
    accentTag: 'async',
  },
  {
    id: 'a03',
    title: 'The Borrow Checker, Mentally Modeled',
    summary: 'Reframing ownership as a graph-coloring problem. Why this changes how you read error messages and design APIs.',
    tags: ['rust', 'memory', 'ownership'],
    kb: 'work',
    age: '2w',
    mtime: 14,
    words: 3210,
    backlinks: 24,
    outlinks: 4,
    indicators: { svg: 4, interactive: 0, code: 9, tables: 1, longread: 1 },
    accentTag: 'memory',
  },
  {
    id: 'a04',
    title: 'Lifetime Annotations: a Visual Tour',
    summary: 'Diagrams for elision, HRTBs, and the dreaded `for<\'a>`. Includes interactive scope visualizer.',
    tags: ['rust', 'lifetimes', 'types'],
    kb: 'work',
    age: '3w',
    mtime: 21,
    words: 2010,
    backlinks: 18,
    outlinks: 6,
    indicators: { svg: 9, interactive: 1, code: 7, tables: 0, longread: 0 },
    accentTag: 'rust',
  },
  {
    id: 'a05',
    title: 'Tokio Task Scheduling Internals',
    summary: 'How the work-stealing scheduler picks tasks, why blocking calls are toxic, and the budgeting trick that prevents starvation.',
    tags: ['rust', 'async', 'tokio'],
    kb: 'work',
    age: '1d',
    mtime: 1,
    words: 5400,
    backlinks: 3,
    outlinks: 14,
    indicators: { svg: 3, interactive: 0, code: 22, tables: 3, longread: 1 },
    accentTag: 'async',
    isNew: true,
  },
  {
    id: 'a06',
    title: 'Channels: MPSC vs Broadcast vs Watch',
    summary: 'Decision tree for picking the right channel. Bench numbers under contention, and the case for hand-rolled rings.',
    tags: ['rust', 'async', 'channels'],
    kb: 'work',
    age: '5d',
    mtime: 5,
    words: 1890,
    backlinks: 9,
    outlinks: 7,
    indicators: { svg: 1, interactive: 0, code: 11, tables: 4, longread: 0 },
    accentTag: 'async',
  },
  {
    id: 'a07',
    title: 'Building a Job Queue from Scratch',
    summary: 'From a Vec<Box<dyn Fn>> in 30 lines to a durable, retrying, observable queue. Each addition justified by a real failure mode.',
    tags: ['rust', 'systems', 'async'],
    kb: 'work',
    age: '1w',
    mtime: 7,
    words: 6200,
    backlinks: 5,
    outlinks: 19,
    indicators: { svg: 2, interactive: 1, code: 28, tables: 2, longread: 1 },
    accentTag: 'systems',
    isNew: true,
  },
  {
    id: 'a08',
    title: 'Cache-Friendly Data Structures',
    summary: 'Why the cache line is the unit of computation. SoA vs AoS, prefetching, and a benchmark harness.',
    tags: ['rust', 'perf', 'systems'],
    kb: 'work',
    age: '2w',
    mtime: 14,
    words: 3700,
    backlinks: 12,
    outlinks: 9,
    indicators: { svg: 5, interactive: 0, code: 13, tables: 6, longread: 1 },
    accentTag: 'perf',
  },
  {
    id: 'a09',
    title: 'Type-Level Programming in Rust',
    summary: 'Phantom types, type-state, and how to encode a state machine the compiler can verify.',
    tags: ['rust', 'types'],
    kb: 'work',
    age: '3w',
    mtime: 21,
    words: 2480,
    backlinks: 8,
    outlinks: 5,
    indicators: { svg: 1, interactive: 0, code: 16, tables: 0, longread: 1 },
    accentTag: 'types',
  },
  {
    id: 'a10',
    title: 'Why Send + Sync Aren\u2019t Auto Sometimes',
    summary: 'The auto-trait propagation rules, demystified. UnsafeCell, raw pointers, and the cases where you must hand-implement.',
    tags: ['rust', 'async', 'types'],
    kb: 'work',
    age: '5d',
    mtime: 5,
    words: 1640,
    backlinks: 4,
    outlinks: 6,
    indicators: { svg: 0, interactive: 0, code: 8, tables: 1, longread: 0 },
    accentTag: 'rust',
  },
  {
    id: 'a11',
    title: 'Allocators 101',
    summary: 'mmap, brk, jemalloc, mimalloc \u2014 how they differ, when it matters, and how to swap them in.',
    tags: ['rust', 'memory', 'perf'],
    kb: 'work',
    age: '1w',
    mtime: 7,
    words: 3050,
    backlinks: 6,
    outlinks: 8,
    indicators: { svg: 3, interactive: 0, code: 6, tables: 4, longread: 1 },
    accentTag: 'memory',
  },
  {
    id: 'a12',
    title: 'Drop, RAII, and Cleanup Patterns',
    summary: 'When Drop runs, when it doesn\u2019t, and the Bomb pattern for catching scopes you didn\u2019t expect to leave.',
    tags: ['rust', 'memory'],
    kb: 'work',
    age: '4w',
    mtime: 28,
    words: 1820,
    backlinks: 14,
    outlinks: 3,
    indicators: { svg: 1, interactive: 0, code: 11, tables: 0, longread: 0 },
    accentTag: 'memory',
  },
  {
    id: 'a13',
    title: 'Async Drop: the Saga',
    summary: 'A history of attempts, why none have shipped, and what you do today: explicit close + linear types.',
    tags: ['rust', 'async'],
    kb: 'work',
    age: '2d',
    mtime: 2,
    words: 2240,
    backlinks: 5,
    outlinks: 11,
    indicators: { svg: 0, interactive: 0, code: 5, tables: 0, longread: 1 },
    accentTag: 'async',
    isNew: true,
  },
  {
    id: 'a14',
    title: 'Profiling Allocator Pressure',
    summary: 'dhat, heaptrack, and a tiny custom counter you can drop into any binary in five minutes.',
    tags: ['rust', 'perf', 'memory'],
    kb: 'work',
    age: '3w',
    mtime: 21,
    words: 2780,
    backlinks: 7,
    outlinks: 4,
    indicators: { svg: 2, interactive: 1, code: 14, tables: 3, longread: 1 },
    accentTag: 'perf',
  },
  {
    id: 'a15',
    title: 'GAT and HRTB: Practical Cases',
    summary: 'Where Generic Associated Types finally let you write the iterator combinator you wanted in 2018.',
    tags: ['rust', 'types'],
    kb: 'work',
    age: '1w',
    mtime: 7,
    words: 1990,
    backlinks: 9,
    outlinks: 6,
    indicators: { svg: 0, interactive: 0, code: 17, tables: 0, longread: 0 },
    accentTag: 'types',
  },
  {
    id: 'a16',
    title: 'Trait Objects vs Generics: Cost Model',
    summary: 'Vtable indirection, monomorphization bloat, and three rules of thumb for picking between them.',
    tags: ['rust', 'types', 'perf'],
    kb: 'work',
    age: '6d',
    mtime: 6,
    words: 2150,
    backlinks: 8,
    outlinks: 7,
    indicators: { svg: 2, interactive: 0, code: 9, tables: 2, longread: 0 },
    accentTag: 'types',
  },
  {
    id: 'a17',
    title: 'Pinning a Future to the Stack',
    summary: 'pin! and tokio::pin!, what they actually do, and why the macro is necessary.',
    tags: ['rust', 'async', 'pin'],
    kb: 'work',
    age: '2w',
    mtime: 14,
    words: 1340,
    backlinks: 4,
    outlinks: 3,
    indicators: { svg: 1, interactive: 0, code: 12, tables: 0, longread: 0 },
    accentTag: 'async',
  },
  {
    id: 'a18',
    title: 'Building a Mini Executor',
    summary: 'A 200-line executor that actually runs futures. Wakers, the task queue, and the `noop_waker` trick.',
    tags: ['rust', 'async', 'systems'],
    kb: 'work',
    age: '3w',
    mtime: 21,
    words: 4900,
    backlinks: 16,
    outlinks: 12,
    indicators: { svg: 4, interactive: 1, code: 31, tables: 1, longread: 1 },
    accentTag: 'async',
  },
  {
    id: 'a19',
    title: 'From `?` to `try_join!`',
    summary: 'Composing fallible futures cleanly. Where try_join, FuturesUnordered, and JoinSet each shine.',
    tags: ['rust', 'errors', 'async'],
    kb: 'work',
    age: '5d',
    mtime: 5,
    words: 1720,
    backlinks: 6,
    outlinks: 9,
    indicators: { svg: 0, interactive: 0, code: 13, tables: 1, longread: 0 },
    accentTag: 'errors',
  },
  {
    id: 'a20',
    title: 'Designing Crash-Safe State Machines',
    summary: 'Append-only logs, idempotent transitions, and the small set of invariants you must never violate.',
    tags: ['rust', 'systems'],
    kb: 'work',
    age: '4w',
    mtime: 28,
    words: 5100,
    backlinks: 19,
    outlinks: 8,
    indicators: { svg: 6, interactive: 0, code: 20, tables: 2, longread: 1 },
    accentTag: 'systems',
  },
];

const TAG_COLORS = {
  rust:     'oklch(0.72 0.14 35)',   // ember
  async:    'oklch(0.72 0.13 240)',  // cool blue
  errors:   'oklch(0.72 0.16 15)',   // red-orange
  memory:   'oklch(0.74 0.13 290)',  // violet
  ownership:'oklch(0.74 0.13 290)',
  pin:      'oklch(0.78 0.13 165)',  // teal
  perf:     'oklch(0.82 0.16 95)',   // amber
  systems:  'oklch(0.74 0.10 145)',  // green
  types:    'oklch(0.78 0.13 320)',  // magenta
  channels: 'oklch(0.72 0.13 240)',
  tokio:    'oklch(0.72 0.13 240)',
  lifetimes:'oklch(0.74 0.13 290)',
};

const TOP_TAGS = [
  ['rust', 20], ['async', 11], ['memory', 5], ['types', 6], ['perf', 4],
  ['systems', 4], ['errors', 2], ['pin', 3], ['ownership', 1], ['tokio', 1],
];

window.ARTIFACTS = ARTIFACTS;
window.TAG_COLORS = TAG_COLORS;
window.TOP_TAGS = TOP_TAGS;
