//! Generates docs/api-routes.md from src/router.rs — the complete
//! METHOD/PATH/handler table the hand-maintained README list kept
//! drifting from. `#[ignore]`d so the normal test sweep skips it; run
//! via `just api-docs`, guard staleness via `just api-docs-check`
//! (mirrors the ts-rs `types` / `types-check` pair).
//!
//! Extraction is regex-over-our-own-rustfmt'd-source, which is robust
//! here because router.rs declares every route through the same
//! `.route("path", method(handler))` shape. The sanity floor below
//! fails the run loudly if a future refactor breaks the pattern,
//! rather than silently writing a shrunken table.

use std::collections::BTreeMap;
use std::path::Path;

/// Routes below this count mean the extractor lost the plot. router.rs
/// declares ~95 `.route` calls / ~99 method registrations today.
const SANITY_FLOOR: usize = 90;

#[test]
#[ignore = "writes docs/api-routes.md — run via `just api-docs`"]
fn generate_api_route_table() {
    let manifest = Path::new(env!("CARGO_MANIFEST_DIR"));
    let router_src = manifest.join("src/router.rs");
    let out_path = manifest.join("../../docs/api-routes.md");
    let src = std::fs::read_to_string(&router_src).expect("read router.rs");

    // Each `.route(` is sliced out by paren-depth scanning (regex spans
    // proved fragile across rustfmt's wrapping); within a call the first
    // quoted string is the path and `verb(handler)` pairs follow.
    // Handlers are plain `routes::module::fn` paths, so a conservative
    // ident-and-colons matcher is enough.
    let method_re =
        regex::Regex::new(r"\b(get|post|put|patch|delete)\s*\(\s*([A-Za-z0-9_:]+)").unwrap();

    // path → (METHOD → handler). BTreeMaps keep the output diff-stable.
    let mut table: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();
    let bytes = src.as_bytes();
    let mut i = 0;
    while let Some(pos) = src[i..].find(".route(") {
        let start = i + pos + ".route(".len();
        let mut depth = 1usize;
        let mut j = start;
        while j < bytes.len() && depth > 0 {
            match bytes[j] {
                b'(' => depth += 1,
                b')' => depth -= 1,
                _ => {}
            }
            j += 1;
        }
        let span = &src[start..j.saturating_sub(1)];
        if let Some(q1) = span.find('"') {
            if let Some(q2) = span[q1 + 1..].find('"') {
                let path = &span[q1 + 1..q1 + 1 + q2];
                // `/healthz` and `/capture` are both mounted on the TOP-LEVEL
                // router (outside the /api nest) — `/healthz` an
                // unauthenticated liveness probe, `/capture` the Web Share
                // Target action (U2 — auth-gated via an explicit
                // `route_layer`, see router.rs). Both are documented in the
                // prose preamble, not the /api table; don't prefix either
                // with /api or count them toward the route total.
                if path != "/healthz" && path != "/capture" {
                    // Everything else declared through `.route` in router.rs
                    // lives under the nested /api tree (the only other non-/api
                    // surfaces are the dispatch fallback and `/capture`, both in
                    // the prose below).
                    let full = format!("/api{path}");
                    for m in method_re.captures_iter(&span[q1 + 1 + q2..]) {
                        table
                            .entry(full.clone())
                            .or_default()
                            .insert(m[1].to_uppercase(), m[2].to_string());
                    }
                }
            }
        }
        i = j;
    }

    let route_count: usize = table.values().map(|m| m.len()).sum();
    assert!(
        route_count >= SANITY_FLOOR,
        "extracted only {route_count} routes from router.rs — the \
         declaration shape changed; fix the extractor in {}",
        file!(),
    );

    let mut out = String::new();
    out.push_str("# HTTP API routes\n\n");
    out.push_str(
        "<!-- GENERATED by `just api-docs` from crates/kb-server/src/router.rs.\n     \
         Do not edit by hand; `just api-docs-check` fails CI when stale. -->\n\n",
    );
    out.push_str(
        "The complete route table, extracted from the router declaration. \
         The narrative API guide (auth, shapes, examples) lives in \
         [docs/http-api.md](http-api.md); generated request/response types live in \
         [web/src/api/generated/](../web/src/api/generated/).\n\n",
    );
    out.push_str(
        "Everything below is served from the `/api` tree (bearer-auth with \
         loopback bypass). Three surfaces sit outside it: the top-level fallback \
         (`<id>.artifacts.<suffix>` hosts dispatch to the sandboxed artifact \
         server, anything else serves the SPA shell); an unauthenticated \
         `GET /healthz` liveness probe (`{status, daemon, uptime_secs, kbs}`) \
         mounted on the top-level router so it bypasses bearer-auth + \
         rate-limiting; and `POST /capture` (U2, v0.25 quick capture) — the Web \
         Share Target action, which the browser posts to bare `/capture` (no \
         `/api` prefix). Despite living outside the nest, `/capture` carries the \
         SAME bearer-auth + loopback bypass as the `/api` tree via an explicit \
         `route_layer` in router.rs; see `routes::capture` for the shared \
         handler core with `POST /api/kb/{kb}/capture` below.\n\n",
    );
    out.push_str("| Method | Path | Handler |\n|---|---|---|\n");
    for (path, methods) in &table {
        for (method, handler) in methods {
            out.push_str(&format!("| {method} | `{path}` | `{handler}` |\n"));
        }
    }
    out.push_str(&format!("\n_{route_count} routes._\n"));

    std::fs::write(&out_path, out).expect("write docs/api-routes.md");
    eprintln!(
        "wrote {} ({} routes)",
        out_path.canonicalize().unwrap_or(out_path).display(),
        route_count
    );
}
