//! V70-A8 (D20 CLI hygiene) — `kb-code tools`: a clap-tree walk that
//! manifests every verb this binary knows about, so an agent doesn't have
//! to read Rust (or 150 `--help` invocations) to learn the surface.
//! Mirrors `crates/kb-cli/src/commands/tools.rs`'s shape (markdown, one
//! section per verb, generated from the SAME `clap::Command` the binary
//! parses with — never hand-maintained, so it cannot drift from what
//! actually runs) — recon `cli-agent-surface.md` open question 1 named
//! this exact precedent.
//!
//! Purely in-process (no daemon round trip, matches D20's "clap-tree
//! walk") — `kb-code tools` works even with no daemon running.
//!
//! # `--json`'s `likely_mutating` field is a HEURISTIC, not a fact
//!
//! D20's fuller ask is a manifest carrying `read_only`/`mutation_class`/
//! `idempotency_key`/`requires_loopback` PER VERB. clap's `Command` tree
//! carries none of that — it is presentation metadata (names, about text,
//! arg shapes), not a route table. Deriving the real answer per verb means
//! cross-referencing ~150 leaf commands against `router.rs`'s HTTP method +
//! gate for each one, by hand, once — a correctness-sensitive audit this
//! unit's one-shot-compile-check budget doesn't cover safely. So `--json`
//! ships ONE best-effort field, [`likely_mutating`], computed from a
//! closed, checked-in list of verb-name FRAGMENTS that tend to denote a
//! mutation (`create`, `apply`, `checkout`, `rotate`, …) — explicitly
//! labelled `"heuristic"` in its own `mutation_confidence` field next to
//! it, in the same spirit as this codebase's exact/likely/candidate trust
//! vocabulary: an approximate signal must say so, never pass as ground
//! truth. `requires_loopback`/`idempotency_key` are NOT included at all
//! (better absent than fabricated) — a future audit that reads `router.rs`
//! once and writes the answers down is the honest way to add them.

use clap::CommandFactory;
use serde_json::json;

/// Verb-name fragments that, when they appear as a LEAF command's own name,
/// usually mean it mutates server or working-tree state. Deliberately a
/// small, readable, checked-in list rather than an attempt at completeness
/// — see the module doc's honesty note. Ordered roughly by frequency in
/// this binary's own surface.
const MUTATING_NAME_FRAGMENTS: &[&str] = &[
    "create",
    "add",
    "new",
    "delete",
    "remove",
    "drop",
    "rm",
    "apply",
    "checkout",
    "rotate",
    "publish",
    "import",
    "ingest",
    "snapshot",
    "gc",
    "sweep",
    "fetch",
    "reopen",
    "edit",
    "resolve",
    "reply",
    "set-intent",
    "set-artifact",
    "disposition",
    "viewed",
    "batch",
    "backfill",
    "sync",
    "start-pr",
    "annotate",
    "rename",
    "trash",
    "untrash",
    "compose",
];

fn likely_mutating(name: &str) -> bool {
    MUTATING_NAME_FRAGMENTS
        .iter()
        .any(|frag| name == *frag || name.contains(frag))
}

/// `kb-code tools [--json]`.
pub fn run(json_out: bool) -> anyhow::Result<()> {
    let cmd = crate::Cli::command();
    if json_out {
        let verbs: Vec<serde_json::Value> = cmd
            .get_subcommands()
            .map(|c| emit_json(c, "kb-code"))
            .collect();
        crate::envelope::print_ok(
            "kbc-cli-tools/1",
            json!({
                "mutation_confidence": "heuristic",
                "note": "likely_mutating is a verb-NAME heuristic, not derived from \
                         router.rs — verify before relying on it for anything \
                         security-relevant. requires_loopback/idempotency_key are \
                         not reported at all (see this module's doc).",
                "verbs": verbs,
            }),
            Vec::new(),
            false,
            None,
        );
        return Ok(());
    }
    println!("# kb-code CLI surface\n");
    println!(
        "Generated by `kb-code tools`. Walks clap's Command tree so the manifest \
         matches the binary. `--json` adds a best-effort (heuristic) mutation \
         classification per verb — see that mode's `mutation_confidence` field.\n"
    );
    for sub in cmd.get_subcommands() {
        emit_md(sub, "kb-code");
    }
    Ok(())
}

fn emit_md(cmd: &clap::Command, parent: &str) {
    let name = cmd.get_name();
    let qualified = format!("{parent} {name}");
    println!("## {qualified}\n");
    if let Some(about) = cmd.get_about() {
        println!("{about}\n");
    }
    println!("```\n{}\n```\n", synopsis(cmd, &qualified));
    for sub in cmd.get_subcommands() {
        emit_md(sub, &qualified);
    }
}

fn emit_json(cmd: &clap::Command, parent: &str) -> serde_json::Value {
    let name = cmd.get_name();
    let qualified = format!("{parent} {name}");
    let args: Vec<serde_json::Value> = cmd
        .get_arguments()
        .filter(|a| {
            !a.is_hide_set() && a.get_id().as_str() != "help" && a.get_id().as_str() != "version"
        })
        .map(|a| {
            json!({
                "id": a.get_id().as_str(),
                "positional": a.is_positional(),
                "required": a.is_required_set(),
                "takes_value": a.get_action().takes_values(),
                "long": a.get_long(),
            })
        })
        .collect();
    json!({
        "verb": qualified,
        "about": cmd.get_about().map(|s| s.to_string()),
        "usage_hint": synopsis(cmd, &qualified),
        "args": args,
        "has_subcommands": cmd.has_subcommands(),
        "likely_mutating": likely_mutating(name),
        "subcommands": cmd
            .get_subcommands()
            .map(|s| emit_json(s, &qualified))
            .collect::<Vec<_>>(),
    })
}

/// Render a one-line synopsis: `kb-code foo <POS> [--flag VALUE]`. Mirrors
/// `kb tools.rs::synopsis` verbatim (same shape, same reasoning — see that
/// module for the "why long-flag-only, why uppercase ids" notes this
/// doesn't repeat).
fn synopsis(cmd: &clap::Command, qualified: &str) -> String {
    let mut out = qualified.to_string();
    for arg in cmd.get_arguments() {
        if arg.is_hide_set() {
            continue;
        }
        let id = arg.get_id().as_str();
        if id == "help" || id == "version" {
            continue;
        }
        let fragment = if arg.is_positional() {
            if arg.is_required_set() {
                format!(" <{}>", id.to_uppercase())
            } else {
                format!(" [{}]", id.to_uppercase())
            }
        } else {
            let long = arg
                .get_long()
                .map(|l| format!("--{l}"))
                .unwrap_or_else(|| format!("--{id}"));
            if arg.get_action().takes_values() {
                format!(" [{long} VALUE]")
            } else {
                format!(" [{long}]")
            }
        };
        out.push_str(&fragment);
    }
    if cmd.has_subcommands() {
        out.push_str(" <SUBCOMMAND>");
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn heuristic_flags_known_mutating_verbs_and_spares_reads() {
        assert!(likely_mutating("checkout"));
        assert!(likely_mutating("create"));
        assert!(likely_mutating("set-artifact"));
        assert!(!likely_mutating("list"));
        assert!(!likely_mutating("show"));
        assert!(!likely_mutating("tools"));
    }

    #[test]
    fn cli_command_tree_walks_without_panicking() {
        // Regression guard: `emit_json` must terminate over the REAL
        // `Cli::command()` tree (recursion depth, `get_long()` on
        // positional args, etc.) — not just over a hand-built fixture.
        let cmd = crate::Cli::command();
        for sub in cmd.get_subcommands() {
            let _ = emit_json(sub, "kb-code");
        }
    }
}
